function l(a,c){this.o=this.F=0;this.S=!1;this.a=this.f=this.h=this.b=this.c=this.v=0;this.j=[0,0,0,0,0,0,0,0];this.A=a;this.l=c;this.Ga=0;l.prototype.ua=function(){var a=0,a=this.c?a|128:a&-129,a=this.f?a|64:a&-65,a=this.h?a|16:a&-17,a=this.b?a|4:a&-5,a=this.a?a|1:a&-2;return(a|2)&-41};l.prototype.T=function(a){this.c=a&128?1:0;this.f=a&64?1:0;this.h=a&16?1:0;this.b=a&4?1:0;this.a=a&1?1:0}}function p(a,c,b){return a.A.read(c&65535,b)&255}function r(a,c,b,e){a.A.write(c&65535,b&255,e)}
function aa(a,c){return p(a,c,!0)|p(a,c+1,!0)<<8}function w(a,c){return 6!=c?a.j[c]:p(a,y(a,4))}function z(a,c,b){b&=255;6!=c?a.j[c]=b:r(a,y(a,4),b)}function y(a,c){return 6!=c?a.j[c]<<8|a.j[c+1]:a.F}function B(a,c,b){6!=c?(z(a,c,b>>8),z(a,c+1,b&255)):a.F=b}
l.prototype.i=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,
1,0,1,1,0,0,1,1,0,1,0,0,1];l.prototype.O=[0,0,1,0,1,0,1,1];l.prototype.va=[0,1,1,1,0,0,0,1];function D(a){return w(a,7)}function I(a){var c=p(a,a.o);a.o=a.o+1&65535;return c}function J(a){return I(a)|I(a)<<8}function ba(a,c){var b=w(a,c),b=b+1&255;z(a,c,b);a.c=0!=(b&128);a.f=0==b;a.h=0==(b&15);a.b=l.prototype.i[b]}function ca(a,c){var b=w(a,c),b=b-1&255;z(a,c,b);a.c=0!=(b&128);a.f=0==b;a.h=15!=(b&15);a.b=l.prototype.i[b]}
function L(a,c,b){var e=D(a);b=e+c+b;c=(e&136)>>1|(c&136)>>2|(b&136)>>3;e=b&255;a.c=0!=(e&128);a.f=0==e;a.h=l.prototype.O[c&7];a.b=l.prototype.i[e];a.a=0!=(b&256);z(a,7,e)}function M(a,c,b){var e=D(a);b=e-c-b&65535;c=(e&136)>>1|(c&136)>>2|(b&136)>>3;e=b&255;a.c=0!=(e&128);a.f=0==e;a.h=!l.prototype.va[c&7];a.b=l.prototype.i[e];a.a=0!=(b&256);z(a,7,e)}function da(a,c){var b=D(a);M(a,c,0);z(a,7,b)}
function ea(a,c){var b=D(a);a.h=0!=((b|c)&8);b&=c;a.c=0!=(b&128);a.f=0==b;a.b=l.prototype.i[b];a.a=0;z(a,7,b)}function fa(a,c){var b=D(a),b=b^c;a.c=0!=(b&128);a.f=0==b;a.h=0;a.b=l.prototype.i[b];a.a=0;z(a,7,b)}function ga(a,c){var b=D(a),b=b|c;a.c=0!=(b&128);a.f=0==b;a.h=0;a.b=l.prototype.i[b];a.a=0;z(a,7,b)}l.prototype.call=function(a){ha(this,this.o);this.o=a};function ia(a){var c=aa(a,a.F);a.F=a.F+2&65535;return c}function ha(a,c){a.F=a.F-2&65535;var b=a.F;r(a,b,c&255,!0);r(a,b+1,c>>8,!0)}
function ja(a,c){var b,e,d,g,f;a.Ga=c;d=c&240;if(118==c||64!=d&&80!=d&&96!=d&&112!=d)switch(c){default:alert("Oops! Unhandled opcode "+c.toString(16));break;case 0:case 8:case 16:case 24:case 32:case 40:case 48:case 56:b=4;break;case 1:case 17:case 33:case 49:b=12;B(a,c>>3,J(a));break;case 2:case 18:b=8;r(a,y(a,c>>3),D(a));break;case 3:case 19:case 35:case 51:b=8;e=c>>3;B(a,e,y(a,e)+1&65535);break;case 4:case 12:case 20:case 28:case 36:case 44:case 60:b=8;ba(a,c>>3);break;case 52:b=12;ba(a,c>>3);
break;case 5:case 13:case 21:case 29:case 37:case 45:case 61:b=8;ca(a,c>>3);break;case 53:b=12;ca(a,c>>3);break;case 6:case 14:case 22:case 30:case 38:case 46:case 62:b=8;z(a,c>>3,I(a));break;case 54:b=12;z(a,c>>3,I(a));break;case 7:b=4;g=D(a);a.a=0!=(g&128);z(a,7,g<<1&255|a.a);break;case 9:case 25:case 41:case 57:b=12;d=y(a,4)+y(a,(c&48)>>3);a.a=0!=(d&65536);z(a,4,d>>8);z(a,5,d&255);break;case 10:case 26:b=8;d=p(a,y(a,(c&16)>>3));z(a,7,d);break;case 11:case 27:case 43:case 59:b=8;e=(c&48)>>3;B(a,
e,y(a,e)-1&65535);break;case 15:b=4;a.a=D(a)&1;d=D(a)>>1|a.a<<7;z(a,7,d);break;case 23:b=4;d=a.a;a.a=0!=(D(a)&128);d=D(a)<<1|d;z(a,7,d);break;case 31:b=4;d=a.a;a.a=D(a)&1;d=D(a)>>1|d<<7;z(a,7,d);break;case 34:b=20;d=J(a);r(a,d,w(a,5));r(a,d+1,w(a,4));break;case 39:b=4;d=a.a;e=0;g=D(a);if(a.h||9<(g&15))e=6;if(a.a||9<g>>4||9<=g>>4&&9<(g&15))e|=96,d=1;L(a,e,0);a.b=l.prototype.i[D(a)];a.a=d;break;case 42:b=20;d=J(a);a.j[5]=p(a,d);a.j[4]=p(a,d+1);break;case 47:b=4;d=D(a)^255;z(a,7,d);break;case 50:b=16;
r(a,J(a),D(a));break;case 55:b=4;a.a=1;break;case 58:b=16;d=p(a,J(a));z(a,7,d);break;case 63:b=4;a.a=!a.a;break;case 118:b=4;a.o=a.o-1&65535;break;case 128:case 129:case 130:case 131:case 132:case 133:case 135:case 136:case 137:case 138:case 139:case 140:case 141:case 143:b=4;d=c&8?a.a:0;L(a,w(a,c&7),d);break;case 134:case 142:b=8;d=c&8?a.a:0;L(a,w(a,c&7),d);break;case 144:case 145:case 146:case 147:case 148:case 149:case 151:case 152:case 153:case 154:case 155:case 156:case 157:case 159:b=4;d=c&
8?a.a:0;M(a,w(a,c&7),d);break;case 150:case 158:b=8;d=c&8?a.a:0;M(a,w(a,c&7),d);break;case 160:case 161:case 162:case 163:case 164:case 165:case 167:b=4;ea(a,w(a,c&7));break;case 166:b=8;ea(a,w(a,c&7));break;case 168:case 169:case 170:case 171:case 172:case 173:case 175:b=4;fa(a,w(a,c&7));break;case 174:b=8;fa(a,w(a,c&7));break;case 176:case 177:case 178:case 179:case 180:case 181:case 183:b=4;ga(a,w(a,c&7));break;case 182:b=8;ga(a,w(a,c&7));break;case 184:case 185:case 186:case 187:case 188:case 189:case 191:b=
4;da(a,w(a,c&7));break;case 190:b=8;da(a,w(a,c&7));break;case 192:case 200:case 208:case 216:case 224:case 232:case 240:case 248:f=[a.f,a.a,a.b,a.c];b=8;f[c>>4&3]==(0!=(c&8))&&(b=16,a.o=ia(a));break;case 193:case 209:case 225:case 241:e=(c&48)>>3;b=12;d=ia(a);6!=e?B(a,e,d):(z(a,7,d>>8),a.T(d&255));break;case 194:case 202:case 210:case 218:case 226:case 234:case 242:case 250:f=[a.f,a.a,a.b,a.c];e=c>>4&3;g=0!=(c&8);b=12;d=J(a);a.o=f[e]==g?d:a.o;break;case 195:case 203:b=12;a.o=J(a);break;case 196:case 204:case 212:case 220:case 228:case 236:case 244:case 252:f=
[a.f,a.a,a.b,a.c];e=c>>4&3;g=0!=(c&8);d=J(a);b=16;f[e]==g&&(b=24,a.call(d));break;case 197:case 213:case 229:case 245:e=(c&48)>>3;b=16;d=6!=e?y(a,e):D(a)<<8|a.ua();ha(a,d);break;case 198:b=8;L(a,I(a),0);break;case 199:case 207:case 215:case 223:case 231:case 239:case 247:case 255:b=16;d=c&56;ha(a,a.o);a.o=d;break;case 201:case 217:b=12;a.o=ia(a);break;case 205:case 221:case 237:case 253:b=24;a.call(J(a));break;case 206:b=8;L(a,I(a),a.a);break;case 211:b=12;d=a.l;e=I(a);g=D(a);switch(e){case 8:case 9:case 10:case 11:N(d.Z,
~e&3,g);break;default:d.f=e,d.i=g}break;case 214:b=8;M(a,I(a),0);break;case 219:b=12;d=a.l.input(I(a));z(a,7,d);break;case 222:b=8;M(a,I(a),a.a);break;case 227:b=24;d=aa(a,a.F);e=a.F;g=y(a,4);r(a,e,g&255,!0);r(a,e+1,g>>8,!0);z(a,5,d&255);z(a,4,d>>8);break;case 230:b=8;ea(a,I(a));break;case 233:b=8;a.o=y(a,4);break;case 235:b=4;d=w(a,5);e=w(a,3);z(a,5,e);z(a,3,d);d=w(a,4);e=w(a,2);z(a,4,e);z(a,2,d);break;case 238:b=8;fa(a,I(a));break;case 243:case 251:b=4;0!=(c&8)?a.v=2:(a.S=!1,a.l.S=!1);break;case 246:b=
8;ga(a,I(a));break;case 249:b=8;a.F=y(a,4);break;case 254:b=8,da(a,I(a))}else src=c&7,dst=c>>3&7,b=8,z(a,dst,w(a,src));0!==a.v&&0===--a.v&&(a.S=!0,a.l.S=!0);a.rb=b};function O(){O.prototype.T=[255,15,255,15,255,15,31,255,31,31,31,255,255,15,255,255];O.prototype.O=[0,.0137,.0205,.0291,.0423,.0618,.0847,.1369,.1691,.2647,.3527,.4499,.5704,.6873,.8482,1];this.reset=function(){this.a=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.i=this.A=this.j=this.b=this.f=this.v=this.l=0;this.h=1;this.c=0};this.reset()}
function ka(a,c){++a.a[c+16]>=(a.a[c<<1]|a.a[1|c<<1]<<8)&&(a.a[c+16]=0,a.j^=1<<c);return((a.a[7]>>c|a.j>>c)&(a.a[7]>>c+3|a.i)&1)*O.prototype.O[a.a[8+c]&16?a.v:a.a[8+c]&15]}
O.prototype.step=function(){if(++this.l>=(this.a[11]<<1|this.a[12]<<9)){this.l=0;var a;a:{if(this.f>>4){if(this.b&1){a=7.5*((this.b>>1^this.b)&2);break a}this.f=0;this.b^=this.b<<1&4}a=this.b&4?this.f++:15-this.f++}this.v=a}++this.A>=this.a[6]<<1&&(this.A=0,this.i=this.h&1,this.h=(this.h^147456*this.i)>>1);return(ka(this,0)+ka(this,1)+ka(this,2))/3};O.prototype.write=function(a,c){1==a?this.c=c&15:(this.a[this.c]=c&O.prototype.T[this.c],13==this.c&&(this.f=0,this.b=c&8?1|c>>1&2|c&4:c))};
O.prototype.read=function(a){return 1==a?this.c:this.a[this.c]};function la(a){this.c=a;this.b=this.a=0}la.prototype.step=function(a){this.b+=a};var P=new function(){this.a=function(a){a=a.toString(16).toUpperCase();return"0".slice(a.length-1)+a};this.b=function(a){a=a.toString(16).toUpperCase();return"000".slice(a.length-1)+a}};function ma(){this.K=0;this.w=this.C="";this.V=this.Va=this.Ua=this.U=0;this.P=[];this.Ta=null;this.Sa=0}function oa(a,c){var b=c.toUpperCase().split(".");a.C=b[0];a.w=b[1];void 0==a.w&&(a.w="");return a}function S(a){this.a=a;this.ka=null;this.Aa=0}function T(a,c){a.ka=[];var b=function(a,b,c){var f;V(a,function(a){if(16>a.K&&a.C===b.C&&a.w===b.w){for(var e in a.P)c.push(a.P[e]);if(128!=a.V)return f=a,!0}});return f}(a.a,c,a.ka);b&&(a.Aa=16384*b.U+128*b.V);return a}
function pa(a){this.m=new Uint8Array(a);for(a=this.m.length;0<=--a;this.m[a]=229);}function qa(a,c){if(a.m.length<c.length){a.m=new Uint8Array(c.length);for(var b=a.m.length;0<=--b;a.m[b]=229);}for(b=c.length;0<=--b;)a.m[b]=c[b];return a}function ra(a,c,b,e){c=10240*c+5120*b+1024*(e-1);return a.m.subarray(c,c+1024)}
function V(a,c){for(var b=40960;45056>b;b+=32){var e=new ma,d=e,g=a.m.subarray(b,b+32),f=0;d.K=g[f];f+=1;d.C=String.fromCharCode.apply(null,g.subarray(f,f+8));f+=8;d.C=d.C.trim();d.w=String.fromCharCode.apply(null,g.subarray(f,f+3));f+=3;d.w=d.w.trim();d.U=g[f];f+=1;d.Ua=g[f];f+=1;d.Va=g[f];f+=1;d.V=g[f];for(var f=f+1,k=g.subarray(f,f+16),f=0;f<k.length;f+=2)d.P.push(255&k[f]|k[f+1]<<8&65280);d.Ta=g;e.Sa=(b-40960)/32;if(c(e))break}}
function sa(a,c){var b=new ma;oa(b,c.toUpperCase());var e;V(a,function(a){return 16>a.K&&a.C===b.C&&a.w===b.w?(e=a,!0):!1});if(e)return T(new S(a),e)}function ta(a){var c=8+Math.floor(a/5);return[c>>1,c%2,1+a%5]}function ua(a,c){var b=new Uint8Array(c.Aa),e=0,d;for(d in c.ka){var g=c.ka[d]<<1;if(2>g)break;for(var f=0;2>f;f++)for(var k=ta(g+f),k=ra(a,k[0],k[1],k[2]),t=0;1024>t;t++)b[e++]=k[t]}return b}function va(a){var c=sa(a,"test.rnd");if(c)return ua(a,c)}
function wa(a){V(a,function(c){if(16>c.K&&0==c.U){var b=T(new S(a),c);console.log(c.C+" "+c.w+" "+b.Aa)}return!1})}function xa(a){var c=new Uint8Array(390);(function(a,b){V(a,function(a){if(16>a.K)for(var c in a.P)b[a.P[c]]=!0;return!1})})(a,c);a=[];for(var b=2;b<c.length;b++)c[b]||a.push(b);return a}
function ya(a,c,b){var e=xa(a);if(e.length<b.length/2048)console.log("Disk full, remaining clusters:",e.length);else if(c=function(a,b,c,d){var e=0,g=0;V(a,function(a){if(16<=a.K){console.log("saveFile: using header ",a.Sa,a.C,a.w);b.V=Math.ceil(d/128);b.U=g;g+=1;128<b.V&&(b.V=128);for(var f=0;8>f;f+=1)b.P[f]=0<d?c[e]:0,0<d&&(d-=2048,e++);a=a.Ta;f=0;a[f++]=b.K;for(var na=b.C+"        ",m=0;8>m;m+=1)a[f+m]=na.charCodeAt(m);f+=8;na=b.w+"   ";for(m=0;3>m;m+=1)a[f+m]=na.charCodeAt(m);f+=3;a[f++]=b.U;
a[f++]=b.Ua;a[f++]=b.Va;a[f++]=b.V;for(m=0;8>m;m++)a[f++]=b.P[m]&255,a[f++]=b.P[m]>>8&255;if(0>=d)return!0}});return e}(a,oa(new ma,c),e,b.length),0!=c)for(var d=0,g=0;g<c&&d<b.length;g+=1)for(var f=e[g]<<1,k=0;2>k;k++)for(var t=ta(f+k),t=ra(a,t[0],t[1],t[2]),x=0;1024>x;x++)t[x]=b[d++]}
function za(a){console.log("List all files:");V(a,function(b){16>b.K&&0==b.U&&console.log("File: ",b.C,".",b.w," header=",b," dirent=",T(new S(a),b))});console.log("Find pip.com:");var c=sa(a,"pip.com");if(c)console.log("Found:",c);else throw"File was not found";var b=ua(a,c),c=[195,206,4,201,0,0,201,0,0,26,0,0,0,0,0,0,40,73,78,80,58,47,79,85,84,58,83,80,65,67,69,41];console.log("Read bytes:",function(a){var b="";for(d in a)b+=a[d].toString(16)+" ";return b}(b.subarray(0,32)));for(var e=!0,d=0;d<
c.length;d+=1)if(e&=b[d]===c[d],!e){console.log("Contents mismatch: expected 0x"+c[d].toString(16)+" got "+b[d].toString(16));debugger}console.log("File reading seems to be ok");console.log("Which clusters are unallocated:");b=xa(a);console.log(b);console.log("Creating new file");b=new Uint8Array(54321);for(d=b.length;0<=--d;b[d]=255*Math.random());ya(a,"test.rnd",b);console.log("List all files:");V(a,function(b){16>b.K&&0==b.U&&console.log("File: ",b.C,".",b.w," header=",b," dirent=",T(new S(a),
b))});console.log("Searching for new file:");c=sa(a,"test.rnd");if(!c){console.log("test.rnd not found");debugger}console.log("found, comparing contents");c=va(a);if(!c){console.log("Could not read file");debugger;throw"";}for(d=0;d<b.length;d++)if(b[d]!==c[d]){console.log("Contents mismatch pos=",d,"expected=",b[d].toString(16),"got=",c[d].toString(16));debugger;throw"";}console.log("Which clusters are unallocated:");b=xa(a);console.log(b);console.log("All tests done");debugger};function W(){this.h=this.I=0;this.i=3;this.c=1;this.j=this.value=0;this.l=!1;this.A=this.v=0;this.f=void 0;this.a=this.b=!1;this.L=0;Aa(this,0)}function Aa(a,c,b){a.J(8);a.L=8;2==(c&4)?a.j=2:3==(c&4)?a.j=3:a.j=c;switch(a.j){case 0:a.c=0;a.l=!0;a.a=!1;break;case 1:a.c=1;a.a=!1;a.l=!0;break;case 2:a.c=1;a.a=!1;break;default:a.c=1,a.a=!1}a.b=!1;a.i=b;a.h=0}
function Ba(a){a.J(0);a.L=0;var c;switch(a.i){case 1:return c=a.I?a.I:a.value,a.I=void 0,c&255;case 2:return c=a.I?a.I:a.value,a.I=void 0,c>>8&255;case 3:switch(c=a.I?a.I:a.value,a.h){case 0:return a.h=1,c&255;case 1:return a.I=void 0,a.h=0,c>>8&255}}return 0}
W.prototype.J=function(a){if(0!==this.L){a-=this.L;if(0>a)return this.L=-a,this.c;this.L=0}switch(this.j){case 0:this.b&&(this.value=this.f,this.a=!0,this.b=!1);this.a&&(this.value-=a,0>=this.value&&(this.value+=65535,this.l&&(this.c=1,this.l=!1)));break;case 1:!this.a&&this.b&&(this.a=!0,a-=3);this.b=!1;this.a&&0<a&&(this.value-=a,0>=this.value&&(this.value+=this.f));break;case 2:!this.a&&this.b&&(this.value=this.f,this.a=!0);this.b=!1;this.a&&0<a&&(this.value-=a,0>=this.value&&(this.value+=this.f));
break;case 3:!this.a&&this.b&&(this.value=this.f,this.a=!0,1==(this.value&1)&&(this.value-=0===this.c?3:1,--a)),this.b=!1,this.a&&0>=(this.value-=a<<1)&&(this.value+=this.f,this.c^=1,1==(this.value&1)&&(this.value-=0===this.c?3:1,this.L=1))}return this.c};function Ca(){this.a=[new W,new W,new W];this.b=0}
function N(a,c,b){switch(c&3){case 3:a.b=b;c=b>>1&3;var e=b>>4&3;b=a.a[b>>6&3];0===e?(b.J(6),b.L=6,b.I=b.value):Aa(b,c,e);break;default:if(a=a.a[c&3],a.J(8),a.L=8,3==a.i)switch(a.h){case 0:a.v=b;a.h=1;break;case 1:a.A=b,a.h=0,a.f=a.A<<8&65535|a.v&255,a.b=!0}else 1==a.i?(a.value=a.value&65280|b,a.value&=65535,a.f=a.value,a.b=!0):2==a.i&&(a.value=a.value&255|b<<8,a.value&=65535,a.f=a.value,a.b=!0)}}Ca.prototype.za=function(a){switch(a&3){case 3:return this.b;default:return Ba(this.a[a&3])}};
Ca.prototype.J=function(a){return this.a[0].J(a)+this.a[1].J(a)+this.a[2].J(a)};function Da(a){this.c=a;this.a=this.b=0}Da.prototype.step=function(a){this.b+=this.c.J(a);this.a+=8};function Ea(a,c,b,e,d){this.S=!1;this.ma=new Uint32Array(16);this.l=a;this.Z=c;this.sb=b;this.b=d;this.O=e;this.ab=function(){};this.Za=function(){};this.Ma=function(){};this.h=function(){};this.c=152;this.a=this.j=this.la=255;this.A=0;this.va=this.ua=this.T=255;this.v=this.i=this.f=void 0}
Ea.prototype.input=function(a){var c=255;switch(a){case 0:c=255;break;case 1:c=this.a&15|16|(this.l.Qa?0:32)|(this.l.hb?0:64)|(this.l.eb?0:128);break;case 2:0!==(this.c&2)?c=this.l.za(~this.la):c=255;break;case 3:c=0===(this.c&16)?0:255;break;case 4:c=this.A;break;case 5:c=this.va;break;case 6:c=this.ua;break;case 7:c=this.T;break;case 8:case 9:case 10:case 11:return this.Z.za(~(a&3));case 20:case 21:c=this.O.read(a&1);break;case 24:c=this.b.read(3);break;case 25:c=this.b.read(2);break;case 26:c=
this.b.read(1);break;case 27:c=this.b.read(0)}return c};fullscreen=function(a){if(document.mozFullScreen||document.webkitIsFullScreen)document.a?document.a():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen();else{var c=document.getElementById("canvasdiv");c.a?c.a():c.mozRequestFullScreen?c.mozRequestFullScreen():c.webkitRequestFullScreen?c.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):1!=a&&alert("Fullscreen not supported. Try Firefox or Chrome.")}};
fullscreener=new function(){this.exec=function(){fullscreen()}};zip.workerScriptsPath="./zip.js/WebContent/";memory=new Fa;
keyboard2=new function(){this.c=new Uint8Array(8);this.eb=this.hb=this.Qa=!1;this.onreset=function(){};this.b=function(a){if(window.event){try{window.event.keyCode=0}catch(c){}window.event.returnValue=!1;window.event.cancelBubble=!0}a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation()};var a=this;this.h=function(b){var c=document.all?event.keyCode:b.which;a.b(b);if(122===c||123===c)a.onreset(122===c);else a.a(c,!1);return!1};this.i=function(b){var c=document.all?event.keyCode:
b.which;a.b(b);122!==c&&123!==c&&a.a(c,!0);return!1};var c={32:[7,128],192:[7,64],221:[7,32],220:[7,16],219:[7,8],90:[7,4],89:[7,2],88:[7,1],87:[6,128],86:[6,64],85:[6,32],84:[6,16],83:[6,8],82:[6,4],81:[6,2],80:[6,1],79:[5,128],78:[5,64],77:[5,32],76:[5,16],75:[5,8],74:[5,4],73:[5,2],72:[5,1],71:[4,128],70:[4,64],69:[4,32],68:[4,16],67:[4,8],66:[4,4],65:[4,2],191:[4,1],191:[3,128],190:[3,64],187:[3,32],188:[3,16],186:[3,8],222:[3,4],57:[3,2],56:[3,1],55:[2,128],54:[2,64],53:[2,32],52:[2,16],51:[2,
8],50:[2,4],49:[2,2],48:[2,1],116:[1,128],115:[1,64],114:[1,32],113:[1,16],112:[1,8],27:[1,4],308:[1,2],220:[1,1],40:[0,128],39:[0,64],38:[0,32],37:[0,16],8:[0,8],13:[0,4],18:[0,2],9:[0,1]};this.a=function(a,e){var d,g,f;d=e?function(a,b,c){a[b]&=~c}:function(a,b,c){a[b]|=c};switch(a){case 16:this.Qa=!e;break;case 17:this.hb=!e;break;case 117:case 91:case 93:this.eb=!e;break;default:8==a&&this.Qa&&(a=308);61==a?a=187:59==a&&(a=186);var k=c[a];k&&(g=k[0],f=k[1]);void 0!==g&&d(this.c,g,f)}};this.za=
function(a){for(var c=0,d=0;8>d;d+=1)0!==(a&1)&&(c|=this.c[d]),a>>=1;return~c&255};this.f=function(){document.onkeypress=function(){return!1};document.onkeydown=this.h;document.onkeyup=this.i}};keyboard2.f();timer=new Ca;ay=new O;
floppy=new (function(){function a(){this.log=!1;this.pa=null;this.Oa=9;this.sa=512;this.Ya=1;this.ra=this.Na=this.da=this.position=this.ta=this.track=this.data=0;this.W=new Uint8Array(6);this.qb={128:0,256:1,512:2,1024:3}}function c(){this.s=!1;this.Ba=[new a,new a,new a,new a];this.fa=0;this.H=this.Ba[0];this.g=this.ea=this.ba=this.u=this.$=this.aa=0;new Uint8Array(8);this.Y=0;this.xa=2;this.D=this.xa+1;this.ga=1}var b={};a.prototype.Fa=function(){return null!==this.pa};a.prototype.Ha=function(a,
b){this.name=a;var c=b.length,f=new Uint8Array(c);if(b){var k;if("string"==typeof b)for(k=0;k<c;k++)f[k]=b.charCodeAt(k);else for(k=0;k<c;k++)f[k]=b[k]}this.pa=f;this.lb()};a.prototype.seek=function(a,b,c){null!==this.pa&&(this.position=(a*this.Oa*this.Ya+this.Oa*c+(0!==b?b-1:0))*this.sa,this.track=a,this.ta=c,console.log("FD1793: disk seek position:",P.b(this.position),"(side:"+this.ta+",trk:"+this.track+",sec:"+b+")"))};a.prototype.nb=function(a){this.Na=this.sa;this.ra=this.da=0;this.fb=a;this.seek(this.track,
this.fb,this.ta)};a.prototype.mb=function(){this.Na=6;this.ra=1;this.da=0;this.W[0]=this.track;this.W[1]=this.ta;this.W[2]=this.fb;this.W[3]=this.qb[this.sa];this.W[4]=0;this.W[5]=0};a.prototype.read=function(){var a=!0;this.da<this.Na?(a=!1,this.data=this.ra?this.W[this.da]:this.pa[this.position+this.da],this.da++):this.log&&console.log("FD1793: read finished src:",this.ra);return a};a.prototype.lb=function(){this.Fa()?(this.Ya=2,this.sa=1024,this.Oa=5):console.warn("FD1793: no disk")};c.prototype.Ha=
function(a,b,c){if(0>a||3<a)throw"FD1793: illegal drive:"+a;this.s&&console.log("FD1793: loadDsk: "+b);this.Ba[a].Ha(b,c)};c.prototype.exec=function(){var a;if(1==this.ea||2==this.ea){if(this.g&2)throw"invalid read";(a=this.H.read())?(this.g&=-2,this.aa=1):(this.g|=2,this.$=this.H.data);this.s&&console.log("FD1793: exec - read done, finished:",a,"data:",P.a(this.$),"status:",P.a(this.g))}else this.g&=-2};c.prototype.read=function(a){var b=0;this.g=this.H.Fa()?this.g&-129:this.g|128;switch(a){case 0:b=
this.g;this.g&1&&(0>this.D?(b&=-2,++this.D):this.D<this.xa?++this.D:this.D===this.xa&&(++this.D,this.exec(),b=this.g));this.aa=0;break;case 1:b=this.u;break;case 2:b=this.ba;break;case 3:this.g&2||console.log("reading too much!");b=this.$;this.g&=-3;this.exec();break;case 4:this.g&1&&this.exec();b=this.aa|(this.g&2?128:0);break;default:console.warn("FD1793: invalid port read");debugger}this.s&&console.log("FD1793: read port:",a,"result:",P.a(b),"status:",P.a(this.g));return b};c.prototype.jb=function(a){var b=
a>>>4,c=a&15,f,k;f=k=c&1;this.ea=this.aa=0;console.log("FD1793: CMD=",P.a(a));switch(b){case 0:this.s&&console.log("FD1793: CMD restore");this.aa=1;this.H.Fa()?(this.u=0,this.H.seek(this.u,1,this.fa)):this.g|=16;break;case 1:this.s&&console.log("FD1793: CMD seek",P.a(c));this.H.seek(this.$,this.ba,this.fa);this.u=this.$;this.aa=1;this.g|=1;this.D=this.Y;break;case 2:case 3:this.s&&console.log("FD1793: CMD step",f);this.u+=this.ga;0>this.u&&(this.u=0);this.D=this.Y;this.g|=1;break;case 4:case 5:this.s&&
console.log("FD1793: CMD step in",f);this.ga=1;this.u+=this.ga;this.D=this.Y;this.g|=1;break;case 6:case 7:this.s&&console.log("FD1793: CMD step out",f);this.ga=-1;this.u+=this.ga;0>this.u&&(this.u=0);this.D=this.Y;this.g|=1;break;case 8:case 9:this.ea=1;this.g|=1;this.H.seek(this.u,this.ba,this.fa);this.H.nb(this.ba);console.log("FD1793: CMD read sector m:",k,"p:",P.a(c),"sector:",this.ba,"status:",P.a(this.g));this.D=this.Y;break;case 10:case 11:this.s&&console.log("FD1793: CMD write sector",k);
break;case 12:this.ea=2;this.g|=1;this.H.mb();this.D=this.Y;this.s&&console.log("FD1793: CMD read address m:",k,"p:",P.a(c),"sector:",P.a(this.g));break;case 13:this.s&&console.log("FD1793: CMD force interrupt");break;case 14:this.s&&console.log("FD1793: CMD read track");break;case 15:this.s&&console.log("FD1793: CMD write track")}};c.prototype.write=function(a,b){switch(a){case 0:this.jb(b);break;case 1:this.s&&console.log("FD1793: set track:",b);this.u=b;this.g&=-3;break;case 2:this.s&&console.log("FD1793: set sector:",
b);this.ba=b;this.g&=-3;break;case 3:this.s&&console.log("FD1793: set data:",P.a(b));this.$=b;this.g&=-3;break;case 4:this.H=this.Ba[b&3];this.fa=~b>>2&1;this.s&&console.log("FD1793: set pr:",P.a(b)," disk select: ",b&3," side: ",this.fa);break;default:console.warn("FD1793: invalid port write");debugger}};b.ib=c;return b}().ib);io=new Ea(keyboard2,timer,memory,ay,floppy);cpu=new l(memory,io);v06c=new Ga;v06c.M=0;var Ha=document.getElementById("frameskip");
v06c.qa=function(a,c){Ha.innerText=v06c.M+" "+c};var X="roms/testtp.rom",Ia="chooser-glass",Ja="about-panel";
if(location.search){X=location.search.substring(1);if("i"===X[0]){document.body.className+=" fullpage";var Ka=document.getElementById("canvasdiv");Ka.className="fullpage";var La=document.getElementById("outerdiv");La.parentNode.replaceChild(Ka,La);var Y=document.getElementById("chooser-panelcontainer");Y.style.position="absolute";Y.style.top="0";Y.style.left="0";Y.className+=" fullpage";Ka.parentNode.appendChild(Y);Ia="chooser-panelcontainer";Y.style.display="none";var Ma=document.getElementById("about-panel");
Ma.className+=" fullpage";Ka.parentNode.appendChild(Ma);Ja="about-panel";X=X.substring(2)}else if("t"==X[0])throw X=X.substring(2),new Z(X,function(){console.log("Loader test - callback ok")},function(){console.log("Loader test - callback error")},function(a){a=qa(new pa,a);za(a)}),v06c.pause(function(){}),"test ended";console.log("user url=",X)}boot=void 0;_onfocus=function(){v06c.Pa.Xa(!1);v06c.ob()};_onblur=function(){v06c.Pa.Xa(!0);v06c.pause(function(){})};
window.addEventListener("load",function(){window.addEventListener("focus",_onfocus);window.addEventListener("blur",_onblur)});keyboard2.onreset=function(a){a&&boot&&Na(boot);v06c.wa(a)};io.h=function(a){window.parent.ruslat&&window.parent.ruslat(a)};var Oa=null;
function Pa(){console.log("loadUserRom url=",X);(new Z(X,function(a,c){v06c.pause(function(){Qa(a,c);v06c.wa(!1)})},function(){console.log("ROM could not be loaded from: ",X)},function(a){console.log("Smells like a floppy image: ",X);floppy.Ha(0,X,a)},Ia,"chooserpanel")).b()}new Z("boot/boots.bin",function(a){boot=a;v06c.pause(function(){Qa([],0);Na(a);v06c.wa(!0);Oa&&(X=Oa);Pa()})},function(){console.log("Cannot load bootloader, not a problem for loading roms")});
about=function(a){aboot=document.getElementById(Ja);a?(aboot.className+=" visible",aboot.style.opacity=1):(aboot.className=aboot.className.substring(0,aboot.className.length-8),aboot.style.opacity=0)};blksbr=function(a){keyboard2.onreset(a)};sideload=function(a){Oa=a};window.parent.registerHooks&&window.parent.registerHooks({about:about,blksbr:blksbr,sideload:sideload});function Fa(){this.m=new Uint8Array(327680);this.ca=void 0;for(var a=0;a<this.m.length;a++)this.m[a]=0;this.Ja=this.Ka=!1;this.cb=this.bb=0}function Ra(a,c,b){if(a.Ja||a.Ka){if(a.Ka&&void 0!==b&&b)return c+(a.cb<<16);if(a.Ja&&40960<=c&&57344>c)return c+(a.bb<<16)}return c}Fa.prototype.read=function(a,c){return this.ca&&a<this.ca.length?this.ca[a]:this.m[Ra(this,a&65535,c)]};Fa.prototype.write=function(a,c,b){this.m[Ra(this,a&65535,b)]=c};
function Qa(a,c){var b=memory,e,d;for(e=b.m.length;0<=--e;)b.m[e]=0;e=0;for(d=a.length;e<d;e++)b.write(c+e,a[e],!1)}function Na(a){var c=memory;c.ca=new Uint8Array(a.length);for(var b=a.length;0<=--b;)c.ca[b]=a[b]};function Z(a,c,b,e,d,g){function f(a){var b={},d;for(d in a)if(b.ia=d,b.target=document.getElementById(a[b.ia]),b.target){if("INPUT"===b.target.tagName){var e=function(b){return function(){var d=document.getElementById(a[b.ia]);console.log("fileSelectHandler e=",d.files[0]);Z.prototype.a&&(Z.prototype.a.style.display="none",Z.prototype.a=void 0);k(d.files[0].name,d.files[0],c);var f=document.createElement("input");f.className="upload";f.type="file";f.name="fileselect[]";f.addEventListener("change",
e);d.parentNode.replaceChild(f,d);f.id="fileselect"}}(b);b.target.addEventListener("change",e,!1)}else"CANVAS"===b.target.tagName&&(b.target.h=function(a){a.preventDefault()},b.target.c=function(a){return function(b){b.preventDefault();a.target.parentNode.className+=" dragover"}}(b),b.target.f=function(a){return function(b){b.preventDefault();b=a.target.parentNode;b.className=b.className.replace(/ dragover/g,"")}}(b),b.target.b=function(a){a.preventDefault()},b.target.i=function(a){return function(b){b.preventDefault();
var d=a.target.parentNode;d.className=d.className.replace(/ dragover/g,"");k(b.dataTransfer.files[0].name,b.dataTransfer.files[0],c)}}(b));b={ia:b.ia,target:b.target}}else console.log("initDrop: cannot find element ",a[b.ia])}function k(a,b,c){zip.createReader(new zip.BlobReader(b),function(a){a.getEntries(function(a){if(a.length){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);1==b.length?R(b[0]):1<b.length&&t(a)}})},function(d){console.log("unzip",d," - trying as rom or fdd");a.toLowerCase().endsWith("fdd")?
G(b,e,0):G(b,c,a.toLowerCase().endsWith("r0m")?0:256)})}function t(a){var b=document.getElementById(d),c=document.getElementById(g),e=document.createElement("div");e.id="buildhdr";c.appendChild(e);e.innerText="[OR BUILD A BOOTABLE FLOPPY IMAGE]";(function(a){e.onclick=function(){b.style.display="none";U(a)}})(a);var f=document.createElement("ul");f.className="romchooser-ol";c.appendChild(f);c.style.height="75vh";for(c=0;c<a.length;c+=1){var m=document.createElement("li"),k=document.createElement("a");
k.href="#";m.appendChild(k);k.innerText=a[c].filename;(function(a){m.onclick=function(){b.style.display="none";R(a)}})(a[c]);m.className=x(a[c].filename)?"chooser-li-rom":a[c].filename.toLowerCase().endsWith("fdd")?"chooser-li-fdd":"chooser-li-wtf";f.appendChild(m)}b.style.display="block";Z.prototype.a=b}function x(a){a=a.toLowerCase();return a.endsWith("rom")||a.endsWith("r0m")||a.endsWith("com")||a.endsWith("bin")}function U(a){new Z("roms/ryba.fdd",function(){},function(){},function(b){var c=qa(new pa(0),
b);console.log("\u0440\u044b\u0431\u0430");if(c)for(var d=a.length,f,m=0;m<a.length;m+=1){var g=function(a){if(a){a=a.toUpperCase()+"\n"+String.fromCharCode(26);for(var b=new Uint8Array(a.length),d=0;d<a.length;d++)b[d]=a.charCodeAt(d);ya(c,"initial.sub",b)}e(c.m,0)};(function(b){b.toLowerCase().endsWith("fdd")?(console.log("Not including ",b),0===--d&&g(f)):(console.log("Extracting ",b),b.toLowerCase().endsWith("com")&&(f=b.toUpperCase().split(".")[0]),E(a[m],function(a){console.log("Saving ",b);
ya(c,b,a);0===--d&&(console.log("All files saved, boot"),wa(c),g(f))},0))})(a[m].filename)}})}function R(a){var b=a.filename.toLowerCase();b.endsWith("rom")||b.endsWith("r0m")||b.endsWith("bin")||b.endsWith("com")?E(a,c,b.endsWith("r0m")||b.endsWith("bin")?0:256):b.endsWith("fdd")&&E(a,e,function(a){var b=a;if(819200>a.length){var b=new Uint8Array(819200),c;for(c=a.length;0<=--c;b[c]=a[c]);for(c=b.length;--c>=a.length;b[c]=229);}return b})}function E(a,b,c){if(a.blob)G(a.blob,b,c);else{console.log("Unzipping ",
a.filename);var d=new zip.BlobWriter("application/octet-stream");a.getData(d,function(a){G(a,b,c)})}}function G(a,b,c){var d=new FileReader;d.addEventListener("loadend",function(){var a=new Uint8Array(d.result);"function"==typeof c?b(c(a),0):b(a,c)});d.readAsArrayBuffer(a)}this.b=function(){var a=["fileselect","canvas"];window.File&&window.FileList&&window.FileReader&&f(a)};(function(a,b,c){var d=a.name;if(d){var e=a.mem,f,g,G=!1;if(d.endsWith("r0m")){f=new ArrayBuffer(e.length);g=new Uint8Array(f);
for(var u=0;u<g.length;u+=1)g[u]=e[u]}else if(d.endsWith("rom")||d.endsWith("com")){f=new ArrayBuffer(e.length-256);g=new Uint8Array(f);G=256;for(u=0;u<g.length;++G,++u)g[u]=e[G];G=d.endsWith("com")}e=new Blob([f],{type:"application/octet-stream"});G?U([{filename:d,blob:e}]):k(a.name,e,b)}else{var q=new XMLHttpRequest;q.open("GET",a,!0);q.responseType="blob";q.onload=function(){k(a,q.response,b)};q.onerror=function(a){console.log("XMLHttpRequest error",a);c()};q.send()}})(a,c,b)};function Sa(a,c){this.l=new la(a);this.O=new Da(c);this.a=this.j=this.i=null;this.f=this.c=this.h=this.A=0;if("undefined"!=typeof AudioContext){console.debug("AudioContext found");this.b=new (window.AudioContext||window.webkitAudioContext);this.j=this.b.sampleRate;this.A=this.j/1497600;this.v=this.b.createScriptProcessor(2048,0,2);this.a=this.b.createGain();this.a.gain.value=1;var b=this;this.v.onaudioprocess=function(a){if(2048<=(b.c-b.f&8191)){var c=a.outputBuffer;a=c.getChannelData(0);for(var c=
c.getChannelData(1),g=b.f,f=b.i,k=0;2048>k;)a[k]=c[k]=f[g],k+=1,g+=1,a[k]=c[k]=f[g],k+=1,g+=1,a[k]=c[k]=f[g],k+=1,g+=1,a[k]=c[k]=f[g],k+=1,g+=1;b.f=g&8191}};this.v.connect(this.a);this.a.connect(this.b.destination);this.T=!0}this.T&&(this.i=new Float32Array(8192));this.Xa=function(a){return function(b){a.a&&(a.a.gain.value=b?0:1)}}(this)};function Ga(){var a=cpu,c=memory,b=io,e=ay,d=!1,g,f=!0;this.M=0;this.ya=c;this.B=a;this.G=b;this.Pa=new Sa(e,this.G.Z);var k,t,x,U=!1;this.Da=function(){if(void 0===this.R||576!=k||288!=t)if(this.R=document.createElement("canvas"),k=this.R.width=576,t=this.R.height=288,this.Ca=this.R.getContext("2d"),console.log("bufferContext=",this.Ca.canvas),this.oa=this.Ca.getImageData(0,0,576,288),this.X.width=1*this.R.width,this.X.height=1*this.R.height,U="undefined"!==typeof Uint8ClampedArray&&this.oa.data.buffer){console.debug("Using native packed graphics");
var a=this.oa.data.buffer;x=new Uint8ClampedArray(a);this.na=new Uint32Array(a)}else{console.debug("Using manually unpacked graphics");x=this.oa.data;for(a=0;a<x.length;a++)x[a]=255;this.na="undefined"!=typeof Int32Array?new Int32Array(165888):Array(165888)}if(!U)for(var b=0,c=0;b<this.na.length;b+=1)a=this.na[b],x[c+0]=a&255,x[c+1]=a>>8&255,x[c+2]=a>>16&255,c+=4;this.Ca.putImageData(this.oa,0,0);this.pb.drawImage(this.R,0,0,this.X.width,this.X.height)};this.Ea=!1;this.ja=new Uint8Array(4);this.Wa=
0;var R=this;this.G.Za=function(a){R.Wa=a};this.Ia=!1;this.G.ab=function(a){R.Ia=a};this.gb=0;this.G.Ma=function(a){R.gb=a};this.ma=this.G.ma;this.N=0;this.$a=function(a,b){for(var c=0,d=0,e=0,f=0,g,k=!1,t=0,u,q,x=!0,E=!1;!k;){u=q=-1;this.Ea&&this.B.S&&(this.Ea=!1,118==this.B.Ga&&(this.B.o+=1),ja(this.B,243),ja(this.B,255),this.N+=16);var F=this.B;ja(F,I(F));F=this.B.Ga;this.N+=this.B.rb;211==F&&(u=this.N-5);-1!=u&&(u=4*u+4,q=u-20);var H,A,v=this.na,Q=this.ma,K=this.Ia;H=0;for(A=this.N<<2;H<A&&!k;H+=
2){g=c-24;if(F=x||128>g||640<=g)g=this.Wa,e=0;else{if(0===(g&15)){g=a;var h=(e&255)<<8|f&255;this.ja[0]=g[32768+h];this.ja[1]=g[40960+h];this.ja[2]=g[49152+h];this.ja[3]=g[57344+h];++e}g=this.ja;h=(g[0]&128)>>4;g[0]<<=1;h|=(g[1]&128)>>5;g[1]<<=1;h|=(g[2]&128)>>6;g[2]<<=1;h|=(g[3]&128)>>7;g[3]<<=1;g=h}if(H===u){K=this.G;if(void 0!==K.f){var h=K,C=K.f,n=K.i;switch(C){case 0:h.c=n;C=h.a&8;0===(h.c&128)?(n=h.c>>1&7,h.a=1===(h.c&1)?h.a|1<<n:h.a&~(1<<n),h.Ma(h.a&1)):h.la=h.j=h.a=0;(h.a&8)!=C&&h.h&&h.h(0===
(h.a&8));break;case 1:C=h.a&8;h.a=n;h.Ma(h.a&1);(h.a&8)!=C&&h.h&&h.h(0===(h.a&8));break;case 2:h.j=n;h.Za(h.j&15);h.ab(0!==(h.j&16));break;case 3:h.la=n;break;case 4:h.A=n;break;case 5:h.va=n;break;case 6:h.ua=n;break;case 7:h.T=n;break;case 12:case 13:case 14:case 15:h.v=n;break;case 16:h=h.sb;h.Ka=0!==(n&16);h.Ja=0!==(n&32);h.bb=(n&3)+1;h.cb=((n&12)>>2)+1;break;case 20:case 21:h.O.write(C&1,n);break;case 24:h.b.write(3,n);break;case 25:h.b.write(2,n);break;case 26:h.b.write(1,n);break;case 27:h.b.write(0,
n);break;case 28:h.b.write(4,n)}K.f=K.i=void 0}K=this.Ia}H===q&&(h=this.G,n=g,C=h.v,void 0===C&&12===h.f&&(C=h.i,h.f=h.i=void 0),void 0!==C&&(h.ma[n]=4278190080|(C&192)>>6<<22|(C&56)>>3<<13|(C&7)<<5,h.v=void 0));E&&(h=c-120,0<=h&&576>h&&(K?(v[t++]=Q[F?g:g&3],v[t++]=Q[F?g:g&12]):(v[t++]=Q[g],v[t++]=Q[g])));c+=2;768===c&&(c=0,d+=1,x||(--f,0>f&&(f=255)),x=40>d||296<=d,E|=b&&24===d,312===d&&(d=0,E=!1,k=!0));40===d&&150===c?f=this.G.la:0===d&&176===c&&this.B.S&&(this.Ea=!0)}u=this.N-(H>>2);q=this.Pa;F=
this.N-u;H=this.gb;q.h+=q.A*F/2;if(1<=q.h){--q.h;A=q.O;v=A.b/A.a;A.b=A.a=0;A=1*v;v=q.l;v.a+=7*v.b;for(g=Q=v.b=0;96<=v.a;v.a-=96)Q+=v.c.step(),g+=1;H=A+Q/g+H+.005*Math.random();A=q;v=A.c+1&8191;v!=A.f&&(A.i[A.c]=H-.5,A.c=v)}q.O.step(F/2);q.l.step(F);this.N=u}};this.kb=function(){this.X=document.getElementById("canvas");this.X.getContext||alert("Your web browser does not support the 'canvas' tag.\nPlease upgrade/change your browser.");this.pb=this.X.getContext("2d");this.R=void 0;this.Da&&this.Da();
console.log("initCanvas: screnCanvas=",this.X)};var E=(new Date).getTime();this.ha=0;this.Ra=2;this.La=function(){var a=50/(this.M+1);this.$a(this.ya.m,!0);for(var b=this.M;0<=--b;)this.$a(this.ya.m,!1);this.Da();var c=E-(new Date).getTime();if(0>c)8>this.M&&0>--this.Ra&&(this.Ra=2,++this.M,a=50/(this.M+1),this.qa&&this.qa(0,-c)),c=0,this.ha=25,E=(new Date).getTime()+1E3/a;else{this.Ra=2;if(0<this.M&&20<c){if(0===this.ha||0===--this.ha)--this.M,this.ha=25,this.qa&&this.qa(0,-c)}else this.ha=25;E+=
1E3/a}d?(d=!1,f=!0,g&&(g(),g=void 0)):function(a){setTimeout(function(){a.La()},c)}(this)};this.kb();this.wa=function(a){f=d=!1;this.B.o=0;this.B.F=0;this.B.S=!1;a||(this.ya.ca=void 0);N(this.G.Z,3,54);N(this.G.Z,3,118);N(this.G.Z,3,182);e.reset();this.La()};this.ob=function(){f=d=!1;this.La()};this.pause=function(a){f?a():(g=a,d=!0)}};
//# sourceMappingURL=vector06js.map
