function p(b,d){this.v=this.H=0;this.S=!1;this.b=this.h=this.i=this.c=this.g=this.s=0;this.m=[0,0,0,0,0,0,0,0];this.A=b;this.o=d;this.xa=0;aa(this);p.prototype.da=function(){var c=0,c=this.g?c|128:c&-129,c=this.h?c|64:c&-65,c=this.i?c|16:c&-17,c=this.c?c|4:c&-5,c=this.b?c|1:c&-2;return(c|2)&-41};p.prototype.T=function(c){this.g=c&128?1:0;this.h=c&64?1:0;this.i=c&16?1:0;this.c=c&4?1:0;this.b=c&1?1:0}}function r(b,d,c){return b.A.read(d&65535,c)&255}function t(b,d,c,h){b.A.write(d&65535,c&255,h)}
function ba(b,d){return r(b,d,!0)|r(b,d+1,!0)<<8}function u(b,d){return 6!=d?b.m[d]:r(b,v(b,4))}function w(b,d,c){c&=255;6!=d?b.m[d]=c:t(b,v(b,4),c)}function v(b,d){return 6!=d?b.m[d]<<8|b.m[d+1]:b.H}function x(b,d,c){6!=d?(w(b,d,c>>8),w(b,d+1,c&255)):b.H=c}
p.prototype.l=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,
1,0,1,1,0,0,1,1,0,1,0,0,1];p.prototype.D=[0,0,1,0,1,0,1,1];p.prototype.ia=[0,1,1,1,0,0,0,1];function y(b){return u(b,7)}function B(b){var d=r(b,b.v);b.v=b.v+1&65535;return d}function C(b){return B(b)|B(b)<<8}function ca(b,d){var c=u(b,d),c=c+1&255;w(b,d,c);b.g=0!=(c&128);b.h=0==c;b.i=0==(c&15);b.c=p.prototype.l[c]}function da(b,d){var c=u(b,d),c=c-1&255;w(b,d,c);b.g=0!=(c&128);b.h=0==c;b.i=15!=(c&15);b.c=p.prototype.l[c]}
function D(b,d,c){var h=y(b);c=h+d+c;d=(h&136)>>1|(d&136)>>2|(c&136)>>3;h=c&255;b.g=0!=(h&128);b.h=0==h;b.i=p.prototype.D[d&7];b.c=p.prototype.l[h];b.b=0!=(c&256);w(b,7,h)}function E(b,d,c){var h=y(b);c=h-d-c&65535;d=(h&136)>>1|(d&136)>>2|(c&136)>>3;h=c&255;b.g=0!=(h&128);b.h=0==h;b.i=!p.prototype.ia[d&7];b.c=p.prototype.l[h];b.b=0!=(c&256);w(b,7,h)}function F(b,d){var c=y(b);E(b,d,0);w(b,7,c)}
function G(b,d){var c=y(b);b.i=0!=((c|d)&8);c&=d;b.g=0!=(c&128);b.h=0==c;b.c=p.prototype.l[c];b.b=0;w(b,7,c)}function H(b,d){var c=y(b),c=c^d;b.g=0!=(c&128);b.h=0==c;b.i=0;b.c=p.prototype.l[c];b.b=0;w(b,7,c)}function I(b,d){var c=y(b),c=c|d;b.g=0!=(c&128);b.h=0==c;b.i=0;b.c=p.prototype.l[c];b.b=0;w(b,7,c)}p.prototype.call=function(b){J(this,this.v);this.v=b};function K(b){var d=ba(b,b.H);b.H=b.H+2&65535;return d}function J(b,d){b.H=b.H-2&65535;var c=b.H;t(b,c,d&255,!0);t(b,c+1,d>>8,!0)}
function aa(b){var d=[];d[0]=d[8]=d[16]=d[24]=d[32]=d[40]=d[48]=d[56]=function(c){return function(){c.f=4;c.a=4}}(b);d[1]=d[17]=d[33]=d[49]=function(c){return function(b){c.f=12;c.a=10;x(c,b>>3,C(c))}}(b);d[2]=d[18]=function(c){return function(b){c.f=8;c.a=7;t(c,v(c,b>>3),y(c))}}(b);d[3]=d[19]=d[35]=d[51]=function(c){return function(b){c.f=8;c.a=5;b>>=3;x(c,b,v(c,b)+1&65535)}}(b);d[4]=d[12]=d[20]=d[28]=d[36]=d[44]=d[60]=function(c){return function(b){c.f=8;c.a=5;ca(c,b>>3)}}(b);d[52]=function(c){return function(b){c.f=
12;c.a=10;ca(c,b>>3)}}(b);d[5]=d[13]=d[21]=d[29]=d[37]=d[45]=d[61]=function(c){return function(b){c.f=8;c.a=5;da(c,b>>3)}}(b);d[53]=function(c){return function(b){c.f=12;c.a=10;da(c,b>>3)}}(b);d[6]=d[14]=d[22]=d[30]=d[38]=d[46]=d[62]=function(c){return function(b){c.f=8;c.a=7;w(c,b>>3,B(c))}}(b);d[54]=function(c){return function(b){c.f=12;c.a=10;w(c,b>>3,B(c))}}(b);d[7]=function(c){return function(){c.f=4;c.a=4;var b=y(c);c.b=0!=(b&128);w(c,7,b<<1&255|c.b)}}(b);d[9]=d[25]=d[41]=d[57]=function(c){return function(b){c.f=
12;c.a=10;b=v(c,4)+v(c,(b&48)>>3);c.b=0!=(b&65536);w(c,4,b>>8);w(c,5,b&255)}}(b);d[10]=d[26]=function(c){return function(b){c.f=8;c.a=7;b=r(c,v(c,(b&16)>>3));w(c,7,b)}}(b);d[11]=d[27]=d[43]=d[59]=function(c){return function(b){c.f=8;c.a=5;b=(b&48)>>3;x(c,b,v(c,b)-1&65535)}}(b);d[15]=function(c){return function(){c.f=4;c.a=4;c.b=y(c)&1;var b=y(c)>>1|c.b<<7;w(c,7,b)}}(b);d[23]=function(c){return function(){c.f=4;c.a=4;var b=c.b;c.b=0!=(y(c)&128);b=y(c)<<1|b;w(c,7,b)}}(b);d[31]=function(c){return function(){c.f=
4;c.a=4;var b=c.b;c.b=y(c)&1;b=y(c)>>1|b<<7;w(c,7,b)}}(b);d[34]=function(c){return function(){c.f=20;c.a=16;var b=C(c);t(c,b,u(c,5));t(c,b+1,u(c,4))}}(b);d[39]=function(c){return function(){c.f=4;c.a=4;var b=c.b,d=0,l=y(c);if(c.i||9<(l&15))d=6;if(c.b||9<l>>4||9<=l>>4&&9<(l&15))d|=96,b=1;D(c,d,0);c.c=p.prototype.l[y(c)];c.b=b}}(b);d[42]=function(c){return function(){c.f=20;c.a=16;var b=C(c);c.m[5]=r(c,b);c.m[4]=r(c,b+1)}}(b);d[47]=function(c){return function(){c.f=4;c.a=4;var b=y(c)^255;w(c,7,b)}}(b);
d[50]=function(c){return function(){c.f=16;c.a=13;t(c,C(c),y(c))}}(b);d[55]=function(c){return function(){c.f=4;c.a=4;c.b=1}}(b);d[58]=function(c){return function(){c.f=16;c.a=13;var b=r(c,C(c));w(c,7,b)}}(b);d[63]=function(c){return function(){c.f=4;c.a=4;c.b=!c.b}}(b);d[118]=function(c){return function(){c.f=4;c.a=4;c.v=c.v-1&65535}}(b);d[128]=d[129]=d[130]=d[131]=d[132]=d[133]=d[135]=d[136]=d[137]=d[138]=d[139]=d[140]=d[141]=d[143]=function(c){return function(b){c.f=4;c.a=4;var d=b&8?c.b:0;D(c,
u(c,b&7),d)}}(b);d[134]=d[142]=function(c){return function(b){c.f=8;c.a=7;var d=b&8?c.b:0;D(c,u(c,b&7),d)}}(b);d[144]=d[145]=d[146]=d[147]=d[148]=d[149]=d[151]=d[152]=d[153]=d[154]=d[155]=d[156]=d[157]=d[159]=function(c){return function(b){c.f=4;c.a=4;var d=b&8?c.b:0;E(c,u(c,b&7),d)}}(b);d[150]=d[158]=function(c){return function(b){c.f=8;c.a=7;var d=b&8?c.b:0;E(c,u(c,b&7),d)}}(b);d[160]=d[161]=d[162]=d[163]=d[164]=d[165]=d[167]=function(c){return function(b){c.f=4;c.a=4;G(c,u(c,b&7))}}(b);d[166]=
function(c){return function(b){c.f=8;c.a=7;G(c,u(c,b&7))}}(b);d[168]=d[169]=d[170]=d[171]=d[172]=d[173]=d[175]=function(c){return function(b){c.f=4;c.a=4;H(c,u(c,b&7))}}(b);d[174]=function(c){return function(b){c.f=8;c.a=7;H(c,u(c,b&7))}}(b);d[176]=d[177]=d[178]=d[179]=d[180]=d[181]=d[183]=function(c){return function(b){c.f=4;c.a=4;I(c,u(c,b&7))}}(b);d[182]=function(c){return function(b){c.f=8;c.a=7;I(c,u(c,b&7))}}(b);d[184]=d[185]=d[186]=d[187]=d[188]=d[189]=d[191]=function(c){return function(b){c.f=
4;c.a=4;F(c,u(c,b&7))}}(b);d[190]=function(c){return function(b){c.f=8;c.a=7;F(c,u(c,b&7))}}(b);d[192]=d[200]=d[208]=d[216]=d[224]=d[232]=d[240]=d[248]=function(c){return function(b){var d=[c.h,c.b,c.c,c.g];c.f=8;c.a=5;d[b>>4&3]==(0!=(b&8))&&(c.a=11,c.f=16,c.v=K(c))}}(b);d[193]=d[209]=d[225]=d[241]=function(c){return function(b){b=(b&48)>>3;c.f=12;c.a=10;var d=K(c);6!=b?x(c,b,d):(w(c,7,d>>8),c.T(d&255))}}(b);d[194]=d[202]=d[210]=d[218]=d[226]=d[234]=d[242]=d[250]=function(c){return function(b){var d=
[c.h,c.b,c.c,c.g],l=b>>4&3;b=0!=(b&8);c.f=12;c.a=10;var g=C(c);c.v=d[l]==b?g:c.v}}(b);d[195]=d[203]=function(c){return function(){c.f=12;c.a=10;c.v=C(c)}}(b);d[196]=d[204]=d[212]=d[220]=d[228]=d[236]=d[244]=d[252]=function(c){return function(b){var d=[c.h,c.b,c.c,c.g],l=b>>4&3;b=0!=(b&8);var g=C(c);c.f=16;c.a=11;d[l]==b&&(c.f=24,c.a=17,c.call(g))}}(b);d[197]=d[213]=d[229]=d[245]=function(c){return function(b){b=(b&48)>>3;c.f=16;c.a=11;b=6!=b?v(c,b):y(c)<<8|c.da();J(c,b)}}(b);d[198]=function(c){return function(){c.f=
8;c.a=7;D(c,B(c),0)}}(b);d[199]=d[207]=d[215]=d[223]=d[231]=d[239]=d[247]=d[255]=function(c){return function(b){c.f=16;c.a=11;b&=56;J(c,c.v);c.v=b}}(b);d[201]=d[217]=function(c){return function(){c.f=12;c.a=10;c.v=K(c)}}(b);d[205]=d[221]=d[237]=d[253]=function(c){return function(){c.f=24;c.a=17;c.call(C(c))}}(b);d[206]=function(c){return function(){c.f=8;c.a=7;D(c,B(c),c.b)}}(b);d[211]=function(c){return function(){c.f=12;c.a=10;var b=c.o,d=B(c),l=y(c);switch(d){case 8:case 9:case 10:case 11:L(b.Y,
~d&3,l);break;default:b.g=d,b.i=l}}}(b);d[214]=function(c){return function(){c.f=8;c.a=7;E(c,B(c),0)}}(b);d[219]=function(c){return function(){c.f=12;c.a=10;var b=c.o.input(B(c));w(c,7,b)}}(b);d[222]=function(c){return function(){c.f=8;c.a=7;E(c,B(c),c.b)}}(b);d[227]=function(c){return function(){c.f=24;c.a=18;var b=ba(c,c.H),d=c.H,l=v(c,4);t(c,d,l&255,!0);t(c,d+1,l>>8,!0);w(c,5,b&255);w(c,4,b>>8)}}(b);d[230]=function(b){return function(){b.f=8;b.a=7;G(b,B(b))}}(b);d[233]=function(b){return function(){b.f=
8;b.a=5;b.v=v(b,4)}}(b);d[235]=function(b){return function(){b.f=4;b.a=4;var d=u(b,5),e=u(b,3);w(b,5,e);w(b,3,d);d=u(b,4);e=u(b,2);w(b,4,e);w(b,2,d)}}(b);d[238]=function(b){return function(){b.f=8;b.a=7;H(b,B(b))}}(b);d[243]=d[251]=function(b){return function(d){b.f=4;b.a=4;0!=(d&8)?b.s=2:(b.S=!1,b.o.S=!1)}}(b);d[246]=function(b){return function(){b.f=8;b.a=7;I(b,B(b))}}(b);d[249]=function(b){return function(){b.f=8;b.a=5;b.H=v(b,4)}}(b);d[254]=function(b){return function(){b.f=8;b.a=7;F(b,B(b))}}(b);
d[64]=d[65]=d[66]=d[67]=d[68]=d[69]=d[70]=d[71]=d[72]=d[73]=d[74]=d[75]=d[76]=d[77]=d[78]=d[79]=d[80]=d[81]=d[82]=d[83]=d[84]=d[85]=d[86]=d[87]=d[88]=d[89]=d[90]=d[91]=d[92]=d[93]=d[94]=d[95]=d[96]=d[97]=d[98]=d[99]=d[100]=d[101]=d[102]=d[103]=d[104]=d[105]=d[106]=d[107]=d[108]=d[109]=d[110]=d[111]=d[112]=d[113]=d[114]=d[115]=d[116]=d[117]=d[119]=d[120]=d[121]=d[122]=d[123]=d[124]=d[125]=d[126]=d[127]=function(b){return function(d){var e=d&7;d=d>>3&7;6==e||6==d?(b.f=8,b.a=7):(b.f=8,b.a=6==e||6==d?
7:5);w(b,d,u(b,e))}}(b);b.K=d}function M(b,d){b.xa=d;var c=b.K[d];c?c(d):alert("Oops! Unhandled opcode "+d.toString(16));0!==b.s&&0===--b.s&&(b.S=!0,b.o.S=!0)};function N(){N.prototype.D=[255,15,255,15,255,15,31,255,31,31,31,255,255,15,255,255];N.prototype.A=[0,.0137,.0205,.0291,.0423,.0618,.0847,.1369,.1691,.2647,.3527,.4499,.5704,.6873,.8482,1];this.reset=function(){this.a=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.i=this.s=this.l=this.b=this.g=this.o=this.m=0;this.h=1;this.c=0};this.reset()}
function O(b,d){++b.a[d+16]>=(b.a[d<<1]|b.a[1|d<<1]<<8)&&(b.a[d+16]=0,b.l^=1<<d);return((b.a[7]>>d|b.l>>d)&(b.a[7]>>d+3|b.i)&1)*N.prototype.A[b.a[8+d]&16?b.o:b.a[8+d]&15]}
N.prototype.step=function(){if(++this.m>=(this.a[11]<<1|this.a[12]<<9)){this.m=0;var b;a:{if(this.g>>4){if(this.b&1){b=7.5*((this.b>>1^this.b)&2);break a}this.g=0;this.b^=this.b<<1&4}b=this.b&4?this.g++:15-this.g++}this.o=b}++this.s>=this.a[6]<<1&&(this.s=0,this.i=this.h&1,this.h=(this.h^147456*this.i)>>1);return(O(this,0)+O(this,1)+O(this,2))/3};N.prototype.write=function(b,d){1==b?this.c=d&15:(this.a[this.c]=d&N.prototype.D[this.c],13==this.c&&(this.g=0,this.b=d&8?1|d>>1&2|d&4:d))};
N.prototype.read=function(b){return 1==b?this.c:this.a[this.c]};function ea(b){this.c=b;this.b=this.a=0}ea.prototype.step=function(b){this.b+=b};var P=new function(){this.a=function(b){b=b.toString(16).toUpperCase();return"0".slice(b.length-1)+b};this.b=function(b){b=b.toString(16).toUpperCase();return"000".slice(b.length-1)+b}};function Q(){this.M=0;this.C=this.F="";this.V=this.Ha=this.Ga=this.U=0;this.R=[];this.Fa=null;this.Ea=0}function fa(b,d){var c=d.toUpperCase().split(".");b.F=c[0];b.C=c[1];void 0==b.C&&(b.C="");return b}function R(b){this.a=b;this.ja=null;this.ta=0}function S(b,d){b.ja=[];var c=function(b,c,d){var g;T(b,function(b){if(16>b.M&&b.F===c.F&&b.C===c.C){for(var h in b.R)d.push(b.R[h]);if(128!=b.V)return g=b,!0}});return g}(b.a,d,b.ja);c&&(b.ta=16384*c.U+128*c.V);return b}
function ga(b){this.u=new Uint8Array(b);for(b=this.u.length;0<=--b;this.u[b]=229);}function ha(b,d){if(b.u.length<d.length){b.u=new Uint8Array(d.length);for(var c=b.u.length;0<=--c;b.u[c]=229);}for(c=d.length;0<=--c;)b.u[c]=d[c];return b}function ia(b,d,c,h){d=10240*d+5120*c+1024*(h-1);return b.u.subarray(d,d+1024)}
function T(b,d){for(var c=40960;45056>c;c+=32){var h=new Q,e=h,l=b.u.subarray(c,c+32),g=0;e.M=l[g];g+=1;e.F=String.fromCharCode.apply(null,l.subarray(g,g+8));g+=8;e.F=e.F.trim();e.C=String.fromCharCode.apply(null,l.subarray(g,g+3));g+=3;e.C=e.C.trim();e.U=l[g];g+=1;e.Ga=l[g];g+=1;e.Ha=l[g];g+=1;e.V=l[g];for(var g=g+1,f=l.subarray(g,g+16),g=0;g<f.length;g+=2)e.R.push(255&f[g]|f[g+1]<<8&65280);e.Fa=l;h.Ea=(c-40960)/32;if(d(h))break}}
function U(b,d){var c=new Q;fa(c,d.toUpperCase());var h;T(b,function(b){return 16>b.M&&b.F===c.F&&b.C===c.C?(h=b,!0):!1});if(h)return S(new R(b),h)}function ja(b){var d=8+Math.floor(b/5);return[d>>1,d%2,1+b%5]}function ka(b,d){var c=new Uint8Array(d.ta),h=0,e;for(e in d.ja){var l=d.ja[e]<<1;if(2>l)break;for(var g=0;2>g;g++)for(var f=ja(l+g),f=ia(b,f[0],f[1],f[2]),q=0;1024>q;q++)c[h++]=f[q]}return c}function la(b){var d=U(b,"test.rnd");if(d)return ka(b,d)}
function ma(b){T(b,function(d){if(16>d.M&&0==d.U){var c=S(new R(b),d);console.log(d.F+" "+d.C+" "+c.ta)}return!1})}function na(b){var d=new Uint8Array(390);(function(b,c){T(b,function(b){if(16>b.M)for(var d in b.R)c[b.R[d]]=!0;return!1})})(b,d);b=[];for(var c=2;c<d.length;c++)d[c]||b.push(c);return b}
function oa(b,d,c){var h=na(b);if(h.length<c.length/2048)console.log("Disk full, remaining clusters:",h.length);else if(d=function(b,c,d,e){var h=0,l=0;T(b,function(b){if(16<=b.M){console.log("saveFile: using header ",b.Ea,b.F,b.C);c.V=Math.ceil(e/128);c.U=l;l+=1;128<c.V&&(c.V=128);for(var f=0;8>f;f+=1)c.R[f]=0<e?d[h]:0,0<e&&(e-=2048,h++);b=b.Fa;f=0;b[f++]=c.M;for(var g=c.F+"        ",k=0;8>k;k+=1)b[f+k]=g.charCodeAt(k);f+=8;g=c.C+"   ";for(k=0;3>k;k+=1)b[f+k]=g.charCodeAt(k);f+=3;b[f++]=c.U;b[f++]=
c.Ga;b[f++]=c.Ha;b[f++]=c.V;for(k=0;8>k;k++)b[f++]=c.R[k]&255,b[f++]=c.R[k]>>8&255;if(0>=e)return!0}});return h}(b,fa(new Q,d),h,c.length),0!=d)for(var e=0,l=0;l<d&&e<c.length;l+=1)for(var g=h[l]<<1,f=0;2>f;f++)for(var q=ja(g+f),q=ia(b,q[0],q[1],q[2]),m=0;1024>m;m++)q[m]=c[e++]}
function pa(b){console.log("List all files:");T(b,function(c){16>c.M&&0==c.U&&console.log("File: ",c.F,".",c.C," header=",c," dirent=",S(new R(b),c))});console.log("Find pip.com:");var d=U(b,"pip.com");if(d)console.log("Found:",d);else throw"File was not found";var c=ka(b,d),d=[195,206,4,201,0,0,201,0,0,26,0,0,0,0,0,0,40,73,78,80,58,47,79,85,84,58,83,80,65,67,69,41];console.log("Read bytes:",function(b){var c="";for(e in b)c+=b[e].toString(16)+" ";return c}(c.subarray(0,32)));for(var h=!0,e=0;e<d.length;e+=
1)if(h&=c[e]===d[e],!h){console.log("Contents mismatch: expected 0x"+d[e].toString(16)+" got "+c[e].toString(16));debugger}console.log("File reading seems to be ok");console.log("Which clusters are unallocated:");c=na(b);console.log(c);console.log("Creating new file");c=new Uint8Array(54321);for(e=c.length;0<=--e;c[e]=255*Math.random());oa(b,"test.rnd",c);console.log("List all files:");T(b,function(c){16>c.M&&0==c.U&&console.log("File: ",c.F,".",c.C," header=",c," dirent=",S(new R(b),c))});console.log("Searching for new file:");
d=U(b,"test.rnd");if(!d){console.log("test.rnd not found");debugger}console.log("found, comparing contents");d=la(b);if(!d){console.log("Could not read file");debugger;throw"";}for(e=0;e<c.length;e++)if(c[e]!==d[e]){console.log("Contents mismatch pos=",e,"expected=",c[e].toString(16),"got=",d[e].toString(16));debugger;throw"";}console.log("Which clusters are unallocated:");c=na(b);console.log(c);console.log("All tests done");debugger};function V(){this.h=this.J=0;this.i=3;this.c=1;this.l=this.value=0;this.m=!1;this.s=this.o=0;this.g=void 0;this.a=this.b=!1;this.N=0;qa(this,0)}function qa(b,d,c){b.L(8);b.N=8;2==(d&4)?b.l=2:3==(d&4)?b.l=3:b.l=d;switch(b.l){case 0:b.c=0;b.m=!0;b.a=!1;break;case 1:b.c=1;b.a=!1;b.m=!0;break;case 2:b.c=1;b.a=!1;break;default:b.c=1,b.a=!1}b.b=!1;b.i=c;b.h=0}
function ra(b){b.L(0);b.N=0;var d;switch(b.i){case 1:return d=b.J?b.J:b.value,b.J=void 0,d&255;case 2:return d=b.J?b.J:b.value,b.J=void 0,d>>8&255;case 3:switch(d=b.J?b.J:b.value,b.h){case 0:return b.h=1,d&255;case 1:return b.J=void 0,b.h=0,d>>8&255}}return 0}
V.prototype.L=function(b){if(0!==this.N){b-=this.N;if(0>b)return this.N=-b,this.c;this.N=0}switch(this.l){case 0:this.b&&(this.value=this.g,this.a=!0,this.b=!1);this.a&&(this.value-=b,0>=this.value&&(this.value+=65535,this.m&&(this.c=1,this.m=!1)));break;case 1:!this.a&&this.b&&(this.a=!0,b-=3);this.b=!1;this.a&&0<b&&(this.value-=b,0>=this.value&&(this.value+=this.g));break;case 2:!this.a&&this.b&&(this.value=this.g,this.a=!0);this.b=!1;this.a&&0<b&&(this.value-=b,0>=this.value&&(this.value+=this.g));
break;case 3:!this.a&&this.b&&(this.value=this.g,this.a=!0,1==(this.value&1)&&(this.value-=0===this.c?3:1,--b)),this.b=!1,this.a&&0>=(this.value-=b<<1)&&(this.value+=this.g,this.c^=1,1==(this.value&1)&&(this.value-=0===this.c?3:1,this.N=1))}return this.c};function sa(){this.a=[new V,new V,new V];this.b=0}
function L(b,d,c){switch(d&3){case 3:b.b=c;d=c>>1&3;var h=c>>4&3;c=b.a[c>>6&3];0===h?(c.L(6),c.N=6,c.J=c.value):qa(c,d,h);break;default:if(b=b.a[d&3],b.L(8),b.N=8,3==b.i)switch(b.h){case 0:b.o=c;b.h=1;break;case 1:b.s=c,b.h=0,b.g=b.s<<8&65535|b.o&255,b.b=!0}else 1==b.i?(b.value=b.value&65280|c,b.value&=65535,b.g=b.value,b.b=!0):2==b.i&&(b.value=b.value&255|c<<8,b.value&=65535,b.g=b.value,b.b=!0)}}sa.prototype.sa=function(b){switch(b&3){case 3:return this.b;default:return ra(this.a[b&3])}};
sa.prototype.L=function(b){return this.a[0].L(b)+this.a[1].L(b)+this.a[2].L(b)};function ta(b){this.c=b;this.a=this.b=0}ta.prototype.step=function(b){this.b+=this.c.L(b);this.a+=8};function ua(b,d,c,h,e){this.S=!1;this.la=new Uint32Array(16);this.m=b;this.Y=d;this.da=c;this.b=e;this.A=h;this.La=function(){};this.Ka=function(){};this.za=function(){};this.h=function(){};this.c=152;this.a=this.l=this.ka=255;this.s=0;this.T=this.K=this.D=255;this.o=this.i=this.g=void 0}
ua.prototype.input=function(b){var d=255;switch(b){case 0:d=255;break;case 1:d=this.a&15|16|(this.m.Da?0:32)|(this.m.Oa?0:64)|(this.m.Ma?0:128);break;case 2:0!==(this.c&2)?d=this.m.sa(~this.ka):d=255;break;case 3:d=0===(this.c&16)?0:255;break;case 4:d=this.s;break;case 5:d=this.T;break;case 6:d=this.K;break;case 7:d=this.D;break;case 8:case 9:case 10:case 11:return this.Y.sa(~(b&3));case 20:case 21:d=this.A.read(b&1);break;case 24:d=this.b.read(3);break;case 25:d=this.b.read(2);break;case 26:d=this.b.read(1);
break;case 27:d=this.b.read(0)}return d};fullscreen=function(b){if(document.mozFullScreen||document.webkitIsFullScreen)document.a?document.a():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen();else{var d=document.getElementById("canvasdiv");d.a?d.a():d.mozRequestFullScreen?d.mozRequestFullScreen():d.webkitRequestFullScreen?d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):1!=b&&alert("Fullscreen not supported. Try Firefox or Chrome.")}};
fullscreener=new function(){this.exec=function(){fullscreen()}};zip.workerScriptsPath="./zip.js/WebContent/";memory=new va;
keyboard2=new function(){this.c=new Uint8Array(8);this.Ma=this.Oa=this.Da=!1;this.onreset=function(){};this.b=function(b){if(window.event){try{window.event.keyCode=0}catch(d){}window.event.returnValue=!1;window.event.cancelBubble=!0}b.preventDefault&&b.preventDefault();b.stopPropagation&&b.stopPropagation()};var b=this;this.h=function(c){var d=document.all?event.keyCode:c.which;b.b(c);if(122===d||123===d)b.onreset(122===d);else b.a(d,!1);return!1};this.i=function(c){var d=document.all?event.keyCode:
c.which;b.b(c);122!==d&&123!==d&&b.a(d,!0);return!1};var d={32:[7,128],192:[7,64],221:[7,32],220:[7,16],219:[7,8],90:[7,4],89:[7,2],88:[7,1],87:[6,128],86:[6,64],85:[6,32],84:[6,16],83:[6,8],82:[6,4],81:[6,2],80:[6,1],79:[5,128],78:[5,64],77:[5,32],76:[5,16],75:[5,8],74:[5,4],73:[5,2],72:[5,1],71:[4,128],70:[4,64],69:[4,32],68:[4,16],67:[4,8],66:[4,4],65:[4,2],191:[4,1],191:[3,128],190:[3,64],187:[3,32],188:[3,16],186:[3,8],222:[3,4],57:[3,2],56:[3,1],55:[2,128],54:[2,64],53:[2,32],52:[2,16],51:[2,
8],50:[2,4],49:[2,2],48:[2,1],116:[1,128],115:[1,64],114:[1,32],113:[1,16],112:[1,8],27:[1,4],308:[1,2],220:[1,1],40:[0,128],39:[0,64],38:[0,32],37:[0,16],8:[0,8],13:[0,4],18:[0,2],9:[0,1]};this.a=function(b,h){var e,l,g;e=h?function(b,c,d){b[c]&=~d}:function(b,c,d){b[c]|=d};switch(b){case 16:this.Da=!h;break;case 17:this.Oa=!h;break;case 117:case 91:case 93:this.Ma=!h;break;default:8==b&&this.Da&&(b=308);61==b?b=187:59==b&&(b=186);var f=d[b];f&&(l=f[0],g=f[1]);void 0!==l&&e(this.c,l,g)}};this.sa=
function(b){for(var d=0,e=0;8>e;e+=1)0!==(b&1)&&(d|=this.c[e]),b>>=1;return~d&255};this.g=function(){document.onkeypress=function(){return!1};document.onkeydown=this.h;document.onkeyup=this.i}};keyboard2.g();timer=new sa;ay=new N;
floppy=new (function(){function b(){this.log=!1;this.ma=null;this.Ba=9;this.oa=512;this.Ja=1;this.na=this.Aa=this.ca=this.position=this.pa=this.track=this.data=0;this.W=new Uint8Array(6);this.Xa={128:0,256:1,512:2,1024:3}}function d(){this.w=!1;this.ua=[new b,new b,new b,new b];this.fa=0;this.I=this.ua[0];this.j=this.ea=this.aa=this.B=this.Z=this.$=0;new Uint8Array(8);this.X=0;this.ra=2;this.G=this.ra+1;this.ga=1}var c={};b.prototype.wa=function(){return null!==this.ma};b.prototype.ya=function(b,
c){this.name=b;var d=c.length,g=new Uint8Array(d);if(c){var f;if("string"==typeof c)for(f=0;f<d;f++)g[f]=c.charCodeAt(f);else for(f=0;f<d;f++)g[f]=c[f]}this.ma=g;this.Ta()};b.prototype.seek=function(b,c,d){null!==this.ma&&(this.position=(b*this.Ba*this.Ja+this.Ba*d+(0!==c?c-1:0))*this.oa,this.track=b,this.pa=d,console.log("FD1793: disk seek position:",P.b(this.position),"(side:"+this.pa+",trk:"+this.track+",sec:"+c+")"))};b.prototype.Va=function(b){this.Aa=this.oa;this.na=this.ca=0;this.Na=b;this.seek(this.track,
this.Na,this.pa)};b.prototype.Ua=function(){this.Aa=6;this.na=1;this.ca=0;this.W[0]=this.track;this.W[1]=this.pa;this.W[2]=this.Na;this.W[3]=this.Xa[this.oa];this.W[4]=0;this.W[5]=0};b.prototype.read=function(){var b=!0;this.ca<this.Aa?(b=!1,this.data=this.na?this.W[this.ca]:this.ma[this.position+this.ca],this.ca++):this.log&&console.log("FD1793: read finished src:",this.na);return b};b.prototype.Ta=function(){this.wa()?(this.Ja=2,this.oa=1024,this.Ba=5):console.warn("FD1793: no disk")};d.prototype.ya=
function(b,c,d){if(0>b||3<b)throw"FD1793: illegal drive:"+b;this.w&&console.log("FD1793: loadDsk: "+c);this.ua[b].ya(c,d)};d.prototype.exec=function(){var b;if(1==this.ea||2==this.ea){if(this.j&2)throw"invalid read";(b=this.I.read())?(this.j&=-2,this.$=1):(this.j|=2,this.Z=this.I.data);this.w&&console.log("FD1793: exec - read done, finished:",b,"data:",P.a(this.Z),"status:",P.a(this.j))}else this.j&=-2};d.prototype.read=function(b){var c=0;this.j=this.I.wa()?this.j&-129:this.j|128;switch(b){case 0:c=
this.j;this.j&1&&(0>this.G?(c&=-2,++this.G):this.G<this.ra?++this.G:this.G===this.ra&&(++this.G,this.exec(),c=this.j));this.$=0;break;case 1:c=this.B;break;case 2:c=this.aa;break;case 3:this.j&2||console.log("reading too much!");c=this.Z;this.j&=-3;this.exec();break;case 4:this.j&1&&this.exec();c=this.$|(this.j&2?128:0);break;default:console.warn("FD1793: invalid port read");debugger}this.w&&console.log("FD1793: read port:",b,"result:",P.a(c),"status:",P.a(this.j));return c};d.prototype.Sa=function(b){var c=
b>>>4,d=b&15,g,f;g=f=d&1;this.ea=this.$=0;console.log("FD1793: CMD=",P.a(b));switch(c){case 0:this.w&&console.log("FD1793: CMD restore");this.$=1;this.I.wa()?(this.B=0,this.I.seek(this.B,1,this.fa)):this.j|=16;break;case 1:this.w&&console.log("FD1793: CMD seek",P.a(d));this.I.seek(this.Z,this.aa,this.fa);this.B=this.Z;this.$=1;this.j|=1;this.G=this.X;break;case 2:case 3:this.w&&console.log("FD1793: CMD step",g);this.B+=this.ga;0>this.B&&(this.B=0);this.G=this.X;this.j|=1;break;case 4:case 5:this.w&&
console.log("FD1793: CMD step in",g);this.ga=1;this.B+=this.ga;this.G=this.X;this.j|=1;break;case 6:case 7:this.w&&console.log("FD1793: CMD step out",g);this.ga=-1;this.B+=this.ga;0>this.B&&(this.B=0);this.G=this.X;this.j|=1;break;case 8:case 9:this.ea=1;this.j|=1;this.I.seek(this.B,this.aa,this.fa);this.I.Va(this.aa);console.log("FD1793: CMD read sector m:",f,"p:",P.a(d),"sector:",this.aa,"status:",P.a(this.j));this.G=this.X;break;case 10:case 11:this.w&&console.log("FD1793: CMD write sector",f);
break;case 12:this.ea=2;this.j|=1;this.I.Ua();this.G=this.X;this.w&&console.log("FD1793: CMD read address m:",f,"p:",P.a(d),"sector:",P.a(this.j));break;case 13:this.w&&console.log("FD1793: CMD force interrupt");break;case 14:this.w&&console.log("FD1793: CMD read track");break;case 15:this.w&&console.log("FD1793: CMD write track")}};d.prototype.write=function(b,c){switch(b){case 0:this.Sa(c);break;case 1:this.w&&console.log("FD1793: set track:",c);this.B=c;this.j&=-3;break;case 2:this.w&&console.log("FD1793: set sector:",
c);this.aa=c;this.j&=-3;break;case 3:this.w&&console.log("FD1793: set data:",P.a(c));this.Z=c;this.j&=-3;break;case 4:this.I=this.ua[c&3];this.fa=~c>>2&1;this.w&&console.log("FD1793: set pr:",P.a(c)," disk select: ",c&3," side: ",this.fa);break;default:console.warn("FD1793: invalid port write");debugger}};c.Ra=d;return c}().Ra);io=new ua(keyboard2,timer,memory,ay,floppy);cpu=new p(memory,io);v06c=new wa;v06c.O=0;var xa=document.getElementById("frameskip");
v06c.s=function(b,d){xa.innerText=v06c.O+" "+d};var W="roms/testtp.rom",ya="chooser-glass",za="about-panel";
if(location.search){W=location.search.substring(1);if("i"===W[0]){document.body.className+=" fullpage";var X=document.getElementById("canvasdiv");X.className="fullpage";var Aa=document.getElementById("outerdiv");Aa.parentNode.replaceChild(X,Aa);var Y=document.getElementById("chooser-panelcontainer");Y.style.position="absolute";Y.style.top="0";Y.style.left="0";Y.className+=" fullpage";X.parentNode.appendChild(Y);ya="chooser-panelcontainer";Y.style.display="none";var Ba=document.getElementById("about-panel");
Ba.className+=" fullpage";X.parentNode.appendChild(Ba);za="about-panel";W=W.substring(2)}else if("t"==W[0])throw W=W.substring(2),new Z(W,function(){console.log("Loader test - callback ok")},function(){console.log("Loader test - callback error")},function(b){b=ha(new ga,b);pa(b)}),v06c.pause(function(){}),"test ended";console.log("user url=",W)}boot=void 0;_onfocus=function(){v06c.Ca.Ia(!1);v06c.Wa()};_onblur=function(){v06c.Ca.Ia(!0);v06c.pause(function(){})};
window.addEventListener("load",function(){window.addEventListener("focus",_onfocus);window.addEventListener("blur",_onblur)});keyboard2.onreset=function(b){b&&boot&&Ca(boot);v06c.qa(b)};io.h=function(b){window.parent.ruslat&&window.parent.ruslat(b)};var Da=null;
function Ea(){console.log("loadUserRom url=",W);(new Z(W,function(b,d){v06c.pause(function(){Fa(b,d);v06c.qa(!1)})},function(){console.log("ROM could not be loaded from: ",W)},function(b){console.log("Smells like a floppy image: ",W);floppy.ya(0,W,b)},ya,"chooserpanel")).b()}new Z("boot/boots.bin",function(b){boot=b;v06c.pause(function(){Fa([],0);Ca(b);v06c.qa(!0);Da&&(W=Da);Ea()})},function(){console.log("Cannot load bootloader, not a problem for loading roms")});
about=function(b){aboot=document.getElementById(za);b?(aboot.className+=" visible",aboot.style.opacity=1):(aboot.className=aboot.className.substring(0,aboot.className.length-8),aboot.style.opacity=0)};blksbr=function(b){keyboard2.onreset(b)};sideload=function(b){Da=b};window.parent.registerHooks&&window.parent.registerHooks({about:about,blksbr:blksbr,sideload:sideload});function va(){this.u=new Uint8Array(327680);this.ba=void 0;for(var b=0;b<this.u.length;b++)this.u[b]=0;this.a=this.b=!1;this.g=this.c=0}function Ga(b,d,c){if(b.a||b.b){if(b.b&&void 0!==c&&c)return d+(b.g<<16);if(b.a&&40960<=d&&57344>d)return d+(b.c<<16)}return d}function Ha(b){return b&491520|b<<2&32764|b>>13&3}va.prototype.read=function(b,d){return this.ba&&b<this.ba.length?this.ba[b]:this.u[Ha(Ga(this,b&65535,d))]};va.prototype.write=function(b,d,c){this.u[Ha(Ga(this,b&65535,c))]=d};
function Fa(b,d){var c=memory,h,e;for(h=c.u.length;0<=--h;)c.u[h]=0;h=0;for(e=b.length;h<e;h++)c.write(d+h,b[h],!1)}function Ca(b){var d=memory;d.ba=new Uint8Array(b.length);for(var c=b.length;0<=--c;)d.ba[c]=b[c]};function Z(b,d,c,h,e,l){function g(b){var c={},e;for(e in b)if(c.ha=e,c.target=document.getElementById(b[c.ha]),c.target){if("INPUT"===c.target.tagName){var h=function(c){return function(){var e=document.getElementById(b[c.ha]);console.log("fileSelectHandler e=",e.files[0]);Z.prototype.a&&(Z.prototype.a.style.display="none",Z.prototype.a=void 0);f(e.files[0].name,e.files[0],d);var g=document.createElement("input");g.className="upload";g.type="file";g.name="fileselect[]";g.addEventListener("change",
h);e.parentNode.replaceChild(g,e);g.id="fileselect"}}(c);c.target.addEventListener("change",h,!1)}else"CANVAS"===c.target.tagName&&(c.target.h=function(b){b.preventDefault()},c.target.c=function(b){return function(c){c.preventDefault();b.target.parentNode.className+=" dragover"}}(c),c.target.g=function(b){return function(c){c.preventDefault();c=b.target.parentNode;c.className=c.className.replace(/ dragover/g,"")}}(c),c.target.b=function(b){b.preventDefault()},c.target.i=function(b){return function(c){c.preventDefault();
var e=b.target.parentNode;e.className=e.className.replace(/ dragover/g,"");f(c.dataTransfer.files[0].name,c.dataTransfer.files[0],d)}}(c));c={ha:c.ha,target:c.target}}else console.log("initDrop: cannot find element ",b[c.ha])}function f(b,c,d){zip.createReader(new zip.BlobReader(c),function(b){b.getEntries(function(b){if(b.length){for(var c=[],d=0;d<b.length;d++)c.push(b[d]);1==c.length?z(c[0]):1<c.length&&q(b)}})},function(e){console.log("unzip",e," - trying as rom or fdd");b.toLowerCase().endsWith("fdd")?
A(c,h,0):A(c,d,b.toLowerCase().endsWith("r0m")?0:256)})}function q(b){var c=document.getElementById(e),d=document.getElementById(l),h=document.createElement("div");h.id="buildhdr";d.appendChild(h);h.innerText="[OR BUILD A BOOTABLE FLOPPY IMAGE]";(function(b){h.onclick=function(){c.style.display="none";k(b)}})(b);var f=document.createElement("ul");f.className="romchooser-ol";d.appendChild(f);d.style.height="75vh";for(d=0;d<b.length;d+=1){var g=document.createElement("li"),n=document.createElement("a");
n.href="#";g.appendChild(n);n.innerText=b[d].filename;(function(b){g.onclick=function(){c.style.display="none";z(b)}})(b[d]);g.className=m(b[d].filename)?"chooser-li-rom":b[d].filename.toLowerCase().endsWith("fdd")?"chooser-li-fdd":"chooser-li-wtf";f.appendChild(g)}c.style.display="block";Z.prototype.a=c}function m(b){b=b.toLowerCase();return b.endsWith("rom")||b.endsWith("r0m")||b.endsWith("com")||b.endsWith("bin")}function k(b){new Z("roms/ryba.fdd",function(){},function(){},function(c){var d=ha(new ga(0),
c);console.log("\u0440\u044b\u0431\u0430");if(d)for(var e=b.length,f,g=0;g<b.length;g+=1){var k=function(b){if(b){b=b.toUpperCase()+"\n"+String.fromCharCode(26);for(var c=new Uint8Array(b.length),e=0;e<b.length;e++)c[e]=b.charCodeAt(e);oa(d,"initial.sub",c)}h(d.u,0)};(function(c){c.toLowerCase().endsWith("fdd")?(console.log("Not including ",c),0===--e&&k(f)):(console.log("Extracting ",c),c.toLowerCase().endsWith("com")&&(f=c.toUpperCase().split(".")[0]),n(b[g],function(b){console.log("Saving ",c);
oa(d,c,b);0===--e&&(console.log("All files saved, boot"),ma(d),k(f))},0))})(b[g].filename)}})}function z(b){var c=b.filename.toLowerCase();c.endsWith("rom")||c.endsWith("r0m")||c.endsWith("bin")||c.endsWith("com")?n(b,d,c.endsWith("r0m")||c.endsWith("bin")?0:256):c.endsWith("fdd")&&n(b,h,function(b){var c=b;if(819200>b.length){var c=new Uint8Array(819200),d;for(d=b.length;0<=--d;c[d]=b[d]);for(d=c.length;--d>=b.length;c[d]=229);}return c})}function n(b,c,d){if(b.blob)A(b.blob,c,d);else{console.log("Unzipping ",
b.filename);var e=new zip.BlobWriter("application/octet-stream");b.getData(e,function(b){A(b,c,d)})}}function A(b,c,d){var e=new FileReader;e.addEventListener("loadend",function(){var b=new Uint8Array(e.result);"function"==typeof d?c(d(b),0):c(b,d)});e.readAsArrayBuffer(b)}this.b=function(){var b=["fileselect","canvas"];window.File&&window.FileList&&window.FileReader&&g(b)};(function(b,c,d){var e=b.name;if(e){var h=b.mem,g,l,n=!1;if(e.endsWith("r0m")){g=new ArrayBuffer(h.length);l=new Uint8Array(g);
for(var m=0;m<l.length;m+=1)l[m]=h[m]}else if(e.endsWith("rom")||e.endsWith("com")){g=new ArrayBuffer(h.length-256);l=new Uint8Array(g);n=256;for(m=0;m<l.length;++n,++m)l[m]=h[n];n=e.endsWith("com")}h=new Blob([g],{type:"application/octet-stream"});n?k([{filename:e,blob:h}]):f(b.name,h,c)}else{var A=new XMLHttpRequest;A.open("GET",b,!0);A.responseType="blob";A.onload=function(){f(b,A.response,c)};A.onerror=function(b){console.log("XMLHttpRequest error",b);d()};A.send()}})(b,d,c)};function Ia(b,d){this.m=new ea(b);this.A=new ta(d);this.a=this.l=this.i=null;this.g=this.c=this.h=this.s=0;if("undefined"!=typeof AudioContext){console.debug("AudioContext found");this.b=new (window.AudioContext||window.webkitAudioContext);this.l=this.b.sampleRate;this.s=this.l/1497600;this.o=this.b.createScriptProcessor(2048,0,2);this.a=this.b.createGain();this.a.gain.value=1;var c=this;this.o.onaudioprocess=function(b){if(2048<=(c.c-c.g&8191)){var d=b.outputBuffer;b=d.getChannelData(0);for(var d=
d.getChannelData(1),l=c.g,g=c.i,f=0;2048>f;)b[f]=d[f]=g[l],f+=1,l+=1,b[f]=d[f]=g[l],f+=1,l+=1,b[f]=d[f]=g[l],f+=1,l+=1,b[f]=d[f]=g[l],f+=1,l+=1;c.g=l&8191}};this.o.connect(this.a);this.a.connect(this.b.destination);this.D=!0}this.D&&(this.i=new Float32Array(8192));this.Ia=function(b){return function(c){b.a&&(b.a.gain.value=c?0:1)}}(this)};function wa(){var b=cpu,d=memory,c=io,h=ay,e=!1,l,g=!0;this.O=0;this.da=d;this.a=b;this.g=c;this.Ca=new Ia(h,this.g.Y);var f,q,m,k=!1;this.D=function(){if(void 0===this.c||576!=f||288!=q)if(this.c=document.createElement("canvas"),f=this.c.width=576,q=this.c.height=288,this.A=this.c.getContext("2d"),console.log("bufferContext=",this.A.canvas),this.o=this.A.getImageData(0,0,576,288),this.i.width=1*this.c.width,this.i.height=1*this.c.height,k="undefined"!==typeof Uint8ClampedArray&&this.o.data.buffer){console.debug("Using native packed graphics");
var b=this.o.data.buffer;m=new Uint8ClampedArray(b);this.l=new Uint32Array(b)}else{console.debug("Using manually unpacked graphics");m=this.o.data;for(b=0;b<m.length;b++)m[b]=255;this.l="undefined"!=typeof Int32Array?new Int32Array(165888):Array(165888)}if(!k)for(var c=0,d=0;c<this.l.length;c+=1)b=this.l[c],m[d+0]=b&255,m[d+1]=b>>8&255,m[d+2]=b>>16&255,d+=4;this.A.putImageData(this.o,0,0);this.Qa.drawImage(this.c,0,0,this.i.width,this.i.height)};this.P=!1;var z=this;this.ia=0;this.g.za=function(b){z.ia=
b};this.la=this.g.la;this.b=0;this.Pa=function(){this.i=document.getElementById("canvas");this.i.getContext||alert("Your web browser does not support the 'canvas' tag.\nPlease upgrade/change your browser.");this.Qa=this.i.getContext("2d");this.c=void 0;this.D&&this.D();console.log("initCanvas: screnCanvas=",this.i)};var n=(new Date).getTime();this.m=0;this.T=2;this.K=function(){var b=50/(this.O+1);Ja(this,!0);for(var c=this.O;0<=--c;)Ja(this,!1);this.D();var d=n-(new Date).getTime();if(0>d)8>this.O&&
0>--this.T&&(this.T=2,++this.O,b=50/(this.O+1),this.s&&this.s(0,-d)),d=0,this.m=25,n=(new Date).getTime()+1E3/b;else{this.T=2;if(0<this.O&&20<d){if(0===this.m||0===--this.m)--this.O,this.m=25,this.s&&this.s(0,-d)}else this.m=25;n+=1E3/b}e?(e=!1,g=!0,l&&(l(),l=void 0)):function(b){setTimeout(function(){b.K()},d)}(this)};this.Pa();this.qa=function(b){g=e=!1;this.a.v=0;this.a.H=0;this.a.S=!1;b||(this.da.ba=void 0);L(this.g.Y,3,54);L(this.g.Y,3,118);L(this.g.Y,3,182);h.reset();this.K()};this.Wa=function(){g=
e=!1;this.K()};this.pause=function(b){g?b():(l=b,e=!0)}}
function Ja(b,d){b.h||(b.h=new Ka(b.l,b.la,b.g,b.da.u));b.h.reset();for(var c,h;!b.h.va;){c=h=-1;var e=b;e.P&&e.a.S&&(e.P=!1,118==e.a.xa&&(e.a.v+=1),M(e.a,243),M(e.a,255),e.b+=16);b.h.P=b.h.P&&b.P;e=b.a;M(e,B(e));e=b.a.xa;b.b+=b.a.f;211==e&&(c=b.b-5);-1!=c&&(c=4*c+4,h=c-20);c=b.h.fill(b.b<<2,c,h,d);b.P=b.a.S&&b.h.P;c=b.b-(c>>2);h=b.Ca;var e=b.b-c,l=b.ia;h.h+=h.s*e/2;if(1<=h.h){--h.h;var g=h.A,f=g.b/g.a;g.b=g.a=0;g=1*f;f=h.m;f.a+=7*f.b;for(var q=f.b=0,m=0;96<=f.a;f.a-=96)q+=f.c.step(),m+=1;l=g+q/m+
l+.005*Math.random();g=h;f=g.c+1&8191;f!=g.g&&(g.i[g.c]=l-.5,g.c=f)}h.A.step(e/2);h.m.step(e);b.b=c}}function Ka(b,d,c,h){this.l=b;this.K=d;this.c=c;this.u=h;this.D=new Uint32Array(h.buffer);this.s=this.m=0;this.reset();var e=this;this.c.Ka=function(b){e.s=b};this.A=!1;this.c.La=function(b){e.A=b}}Ka.prototype.reset=function(){this.g=this.i=this.a=this.b=0;this.o=!0;this.visible=!1;this.h=0;this.P=this.va=!1};
Ka.prototype.fill=function(b,d,c,h){var e=this.l,l=this.K,g;for(g=0;g<b&&!this.va;g+=2){var f=this.b-24,q=this.o||128>f||640<=f;q?(this.i=0,f=this.s):(0===(f&15)&&(this.m=this.D[8192+((this.i&255)<<8|this.g&255)],++this.i),f=this.m,this.m=f<<1,f=f>>4&8|f>>13&4|f>>22&2|f>>31&1);if(g===d){var m=this.c;if(void 0!==m.g){var k=m,z=m.g,n=m.i;switch(z){case 0:k.c=n;z=k.a&8;0===(k.c&128)?(n=k.c>>1&7,k.a=1===(k.c&1)?k.a|1<<n:k.a&~(1<<n),k.za(k.a&1)):k.ka=k.l=k.a=0;(k.a&8)!=z&&k.h&&k.h(0===(k.a&8));break;case 1:z=
k.a&8;k.a=n;k.za(k.a&1);(k.a&8)!=z&&k.h&&k.h(0===(k.a&8));break;case 2:k.l=n;k.Ka(k.l&15);k.La(0!==(k.l&16));break;case 3:k.ka=n;break;case 4:k.s=n;break;case 5:k.T=n;break;case 6:k.K=n;break;case 7:k.D=n;break;case 12:case 13:case 14:case 15:k.o=n;break;case 16:k=k.da;k.b=0!==(n&16);k.a=0!==(n&32);k.c=(n&3)+1;k.g=((n&12)>>2)+1;break;case 20:case 21:k.A.write(z&1,n);break;case 24:k.b.write(3,n);break;case 25:k.b.write(2,n);break;case 26:k.b.write(1,n);break;case 27:k.b.write(0,n);break;case 28:k.b.write(4,
n)}m.g=m.i=void 0}}g===c&&(m=this.c,k=m.o,void 0===k&&12===m.g&&(k=m.i,m.g=m.i=void 0),void 0!==k&&(m.la[f]=4278190080|(k&192)>>6<<22|(k&56)>>3<<13|(k&7)<<5,m.o=void 0));this.visible&&(m=this.b-120,0<=m&&576>m&&(this.A&&!q?(e[this.h++]=l[f&3],e[this.h++]=l[f&12]):(q=l[f],e[this.h++]=q,e[this.h++]=q)));this.b+=2;768===this.b&&(q=h,this.b=0,this.a+=1,--this.g,!this.o&&0>this.g&&(this.g=255),this.o=40>this.a||296<=this.a,this.visible=this.visible||q&&24===this.a,312===this.a&&(this.a=0,this.visible=
!1,this.va=!0));40===this.a&&150===this.b?this.g=this.c.ka:0===this.a&&176===this.b&&(this.P=!0)}return g};
//# sourceMappingURL=vector06js.map
