function n(a,c){this.u=this.G=0;this.P=!1;this.a=this.f=this.g=this.b=this.c=this.m=0;this.j=[0,0,0,0,0,0,0,0];this.o=a;this.l=c;this.va=0;n.prototype.R=function(){var a=0,a=this.c?a|128:a&-129,a=this.f?a|64:a&-65,a=this.g?a|16:a&-17,a=this.b?a|4:a&-5,a=this.a?a|1:a&-2;return(a|2)&-41};n.prototype.C=function(a){this.c=a&128?1:0;this.f=a&64?1:0;this.g=a&16?1:0;this.b=a&4?1:0;this.a=a&1?1:0}}function q(a,c,b){return a.o.read(c&65535,b)&255}function r(a,c,b,e){a.o.write(c&65535,b&255,e)}
function aa(a,c){return q(a,c,!0)|q(a,c+1,!0)<<8}function t(a,c){return 6!=c?a.j[c]:q(a,u(a,4))}function v(a,c,b){b&=255;6!=c?a.j[c]=b:r(a,u(a,4),b)}function u(a,c){return 6!=c?a.j[c]<<8|a.j[c+1]:a.G}function w(a,c,b){6!=c?(v(a,c,b>>8),v(a,c+1,b&255)):a.G=b}
n.prototype.h=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,
1,0,1,1,0,0,1,1,0,1,0,0,1];n.prototype.A=[0,0,1,0,1,0,1,1];n.prototype.S=[0,1,1,1,0,0,0,1];function x(a){return t(a,7)}function A(a){var c=q(a,a.u);a.u=a.u+1&65535;return c}function B(a){return A(a)|A(a)<<8}function ba(a,c){var b=t(a,c),b=b+1&255;v(a,c,b);a.c=0!=(b&128);a.f=0==b;a.g=0==(b&15);a.b=n.prototype.h[b]}function ca(a,c){var b=t(a,c),b=b-1&255;v(a,c,b);a.c=0!=(b&128);a.f=0==b;a.g=15!=(b&15);a.b=n.prototype.h[b]}
function C(a,c,b){var e=x(a);b=e+c+b;c=(e&136)>>1|(c&136)>>2|(b&136)>>3;e=b&255;a.c=0!=(e&128);a.f=0==e;a.g=n.prototype.A[c&7];a.b=n.prototype.h[e];a.a=0!=(b&256);v(a,7,e)}function D(a,c,b){var e=x(a);b=e-c-b&65535;c=(e&136)>>1|(c&136)>>2|(b&136)>>3;e=b&255;a.c=0!=(e&128);a.f=0==e;a.g=!n.prototype.S[c&7];a.b=n.prototype.h[e];a.a=0!=(b&256);v(a,7,e)}function E(a,c){var b=x(a);D(a,c,0);v(a,7,b)}
function F(a,c){var b=x(a);a.g=0!=((b|c)&8);b&=c;a.c=0!=(b&128);a.f=0==b;a.b=n.prototype.h[b];a.a=0;v(a,7,b)}function G(a,c){var b=x(a),b=b^c;a.c=0!=(b&128);a.f=0==b;a.g=0;a.b=n.prototype.h[b];a.a=0;v(a,7,b)}function H(a,c){var b=x(a),b=b|c;a.c=0!=(b&128);a.f=0==b;a.g=0;a.b=n.prototype.h[b];a.a=0;v(a,7,b)}n.prototype.call=function(a){I(this,this.u);this.u=a};function J(a){var c=aa(a,a.G);a.G=a.G+2&65535;return c}function I(a,c){a.G=a.G-2&65535;var b=a.G;r(a,b,c&255,!0);r(a,b+1,c>>8,!0)}
function K(a,c){var b,e,d,k,g;a.va=c;d=c&240;if(118==c||64!=d&&80!=d&&96!=d&&112!=d)switch(c){default:alert("Oops! Unhandled opcode "+c.toString(16));break;case 0:case 8:case 16:case 24:case 32:case 40:case 48:case 56:b=4;break;case 1:case 17:case 33:case 49:b=12;w(a,c>>3,B(a));break;case 2:case 18:b=8;r(a,u(a,c>>3),x(a));break;case 3:case 19:case 35:case 51:b=8;e=c>>3;w(a,e,u(a,e)+1&65535);break;case 4:case 12:case 20:case 28:case 36:case 44:case 60:b=8;ba(a,c>>3);break;case 52:b=12;ba(a,c>>3);break;
case 5:case 13:case 21:case 29:case 37:case 45:case 61:b=8;ca(a,c>>3);break;case 53:b=12;ca(a,c>>3);break;case 6:case 14:case 22:case 30:case 38:case 46:case 62:b=8;v(a,c>>3,A(a));break;case 54:b=12;v(a,c>>3,A(a));break;case 7:b=4;k=x(a);a.a=0!=(k&128);v(a,7,k<<1&255|a.a);break;case 9:case 25:case 41:case 57:b=12;d=u(a,4)+u(a,(c&48)>>3);a.a=0!=(d&65536);v(a,4,d>>8);v(a,5,d&255);break;case 10:case 26:b=8;d=q(a,u(a,(c&16)>>3));v(a,7,d);break;case 11:case 27:case 43:case 59:b=8;e=(c&48)>>3;w(a,e,u(a,
e)-1&65535);break;case 15:b=4;a.a=x(a)&1;d=x(a)>>1|a.a<<7;v(a,7,d);break;case 23:b=4;d=a.a;a.a=0!=(x(a)&128);d=x(a)<<1|d;v(a,7,d);break;case 31:b=4;d=a.a;a.a=x(a)&1;d=x(a)>>1|d<<7;v(a,7,d);break;case 34:b=20;d=B(a);r(a,d,t(a,5));r(a,d+1,t(a,4));break;case 39:b=4;d=a.a;e=0;k=x(a);if(a.g||9<(k&15))e=6;if(a.a||9<k>>4||9<=k>>4&&9<(k&15))e|=96,d=1;C(a,e,0);a.b=n.prototype.h[x(a)];a.a=d;break;case 42:b=20;d=B(a);a.j[5]=q(a,d);a.j[4]=q(a,d+1);break;case 47:b=4;d=x(a)^255;v(a,7,d);break;case 50:b=16;r(a,
B(a),x(a));break;case 55:b=4;a.a=1;break;case 58:b=16;d=q(a,B(a));v(a,7,d);break;case 63:b=4;a.a=!a.a;break;case 118:b=4;a.u=a.u-1&65535;break;case 128:case 129:case 130:case 131:case 132:case 133:case 135:case 136:case 137:case 138:case 139:case 140:case 141:case 143:b=4;d=c&8?a.a:0;C(a,t(a,c&7),d);break;case 134:case 142:b=8;d=c&8?a.a:0;C(a,t(a,c&7),d);break;case 144:case 145:case 146:case 147:case 148:case 149:case 151:case 152:case 153:case 154:case 155:case 156:case 157:case 159:b=4;d=c&8?a.a:
0;D(a,t(a,c&7),d);break;case 150:case 158:b=8;d=c&8?a.a:0;D(a,t(a,c&7),d);break;case 160:case 161:case 162:case 163:case 164:case 165:case 167:b=4;F(a,t(a,c&7));break;case 166:b=8;F(a,t(a,c&7));break;case 168:case 169:case 170:case 171:case 172:case 173:case 175:b=4;G(a,t(a,c&7));break;case 174:b=8;G(a,t(a,c&7));break;case 176:case 177:case 178:case 179:case 180:case 181:case 183:b=4;H(a,t(a,c&7));break;case 182:b=8;H(a,t(a,c&7));break;case 184:case 185:case 186:case 187:case 188:case 189:case 191:b=
4;E(a,t(a,c&7));break;case 190:b=8;E(a,t(a,c&7));break;case 192:case 200:case 208:case 216:case 224:case 232:case 240:case 248:g=[a.f,a.a,a.b,a.c];b=8;g[c>>4&3]==(0!=(c&8))&&(b=16,a.u=J(a));break;case 193:case 209:case 225:case 241:e=(c&48)>>3;b=12;d=J(a);6!=e?w(a,e,d):(v(a,7,d>>8),a.C(d&255));break;case 194:case 202:case 210:case 218:case 226:case 234:case 242:case 250:g=[a.f,a.a,a.b,a.c];e=c>>4&3;k=0!=(c&8);b=12;d=B(a);a.u=g[e]==k?d:a.u;break;case 195:case 203:b=12;a.u=B(a);break;case 196:case 204:case 212:case 220:case 228:case 236:case 244:case 252:g=
[a.f,a.a,a.b,a.c];e=c>>4&3;k=0!=(c&8);d=B(a);b=16;g[e]==k&&(b=24,a.call(d));break;case 197:case 213:case 229:case 245:e=(c&48)>>3;b=16;d=6!=e?u(a,e):x(a)<<8|a.R();I(a,d);break;case 198:b=8;C(a,A(a),0);break;case 199:case 207:case 215:case 223:case 231:case 239:case 247:case 255:b=16;d=c&56;I(a,a.u);a.u=d;break;case 201:case 217:b=12;a.u=J(a);break;case 205:case 221:case 237:case 253:b=24;a.call(B(a));break;case 206:b=8;C(a,A(a),a.a);break;case 211:b=12;d=a.l;e=A(a);k=x(a);switch(e){case 8:case 9:case 10:case 11:L(d.X,
~e&3,k);break;default:d.f=e,d.h=k}break;case 214:b=8;D(a,A(a),0);break;case 219:b=12;d=a.l.input(A(a));v(a,7,d);break;case 222:b=8;D(a,A(a),a.a);break;case 227:b=24;d=aa(a,a.G);e=a.G;k=u(a,4);r(a,e,k&255,!0);r(a,e+1,k>>8,!0);v(a,5,d&255);v(a,4,d>>8);break;case 230:b=8;F(a,A(a));break;case 233:b=8;a.u=u(a,4);break;case 235:b=4;d=t(a,5);e=t(a,3);v(a,5,e);v(a,3,d);d=t(a,4);e=t(a,2);v(a,4,e);v(a,2,d);break;case 238:b=8;G(a,A(a));break;case 243:case 251:b=4;0!=(c&8)?a.m=2:(a.P=!1,a.l.P=!1);break;case 246:b=
8;H(a,A(a));break;case 249:b=8;a.G=u(a,4);break;case 254:b=8,E(a,A(a))}else src=c&7,dst=c>>3&7,b=8,v(a,dst,t(a,src));0!==a.m&&0===--a.m&&(a.P=!0,a.l.P=!0);a.ab=b};function M(){M.prototype.C=[255,15,255,15,255,15,31,255,31,31,31,255,255,15,255,255];M.prototype.A=[0,.0137,.0205,.0291,.0423,.0618,.0847,.1369,.1691,.2647,.3527,.4499,.5704,.6873,.8482,1];this.reset=function(){this.a=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.h=this.o=this.j=this.b=this.f=this.m=this.l=0;this.g=1;this.c=0};this.reset()}
function N(a,c){++a.a[c+16]>=(a.a[c<<1]|a.a[1|c<<1]<<8)&&(a.a[c+16]=0,a.j^=1<<c);return((a.a[7]>>c|a.j>>c)&(a.a[7]>>c+3|a.h)&1)*M.prototype.A[a.a[8+c]&16?a.m:a.a[8+c]&15]}
M.prototype.step=function(){if(++this.l>=(this.a[11]<<1|this.a[12]<<9)){this.l=0;var a;a:{if(this.f>>4){if(this.b&1){a=7.5*((this.b>>1^this.b)&2);break a}this.f=0;this.b^=this.b<<1&4}a=this.b&4?this.f++:15-this.f++}this.m=a}++this.o>=this.a[6]<<1&&(this.o=0,this.h=this.g&1,this.g=(this.g^147456*this.h)>>1);return(N(this,0)+N(this,1)+N(this,2))/3};M.prototype.write=function(a,c){1==a?this.c=c&15:(this.a[this.c]=c&M.prototype.C[this.c],13==this.c&&(this.f=0,this.b=c&8?1|c>>1&2|c&4:c))};
M.prototype.read=function(a){return 1==a?this.c:this.a[this.c]};function da(a){this.c=a;this.b=this.a=0}da.prototype.step=function(a){this.b+=a};var O=new function(){this.a=function(a){a=a.toString(16).toUpperCase();return"0".slice(a.length-1)+a};this.b=function(a){a=a.toString(16).toUpperCase();return"000".slice(a.length-1)+a}};function P(){this.K=0;this.B=this.D="";this.U=this.Ia=this.Ha=this.T=0;this.O=[];this.Ga=null;this.Fa=0}function ea(a,c){var b=c.toUpperCase().split(".");a.D=b[0];a.B=b[1];void 0==a.B&&(a.B="");return a}function Q(a){this.a=a;this.ga=null;this.ra=0}function R(a,c){a.ga=[];var b=function(a,b,c){var g;S(a,function(a){if(16>a.K&&a.D===b.D&&a.B===b.B){for(var e in a.O)c.push(a.O[e]);if(128!=a.U)return g=a,!0}});return g}(a.a,c,a.ga);b&&(a.ra=16384*b.T+128*b.U);return a}
function fa(a){this.s=new Uint8Array(a);for(a=this.s.length;0<=--a;this.s[a]=229);}function ga(a,c){if(a.s.length<c.length){a.s=new Uint8Array(c.length);for(var b=a.s.length;0<=--b;a.s[b]=229);}for(b=c.length;0<=--b;)a.s[b]=c[b];return a}function ha(a,c,b,e){c=10240*c+5120*b+1024*(e-1);return a.s.subarray(c,c+1024)}
function S(a,c){for(var b=40960;45056>b;b+=32){var e=new P,d=e,k=a.s.subarray(b,b+32),g=0;d.K=k[g];g+=1;d.D=String.fromCharCode.apply(null,k.subarray(g,g+8));g+=8;d.D=d.D.trim();d.B=String.fromCharCode.apply(null,k.subarray(g,g+3));g+=3;d.B=d.B.trim();d.T=k[g];g+=1;d.Ha=k[g];g+=1;d.Ia=k[g];g+=1;d.U=k[g];for(var g=g+1,f=k.subarray(g,g+16),g=0;g<f.length;g+=2)d.O.push(255&f[g]|f[g+1]<<8&65280);d.Ga=k;e.Fa=(b-40960)/32;if(c(e))break}}
function T(a,c){var b=new P;ea(b,c.toUpperCase());var e;S(a,function(a){return 16>a.K&&a.D===b.D&&a.B===b.B?(e=a,!0):!1});if(e)return R(new Q(a),e)}function ia(a){var c=8+Math.floor(a/5);return[c>>1,c%2,1+a%5]}function ja(a,c){var b=new Uint8Array(c.ra),e=0,d;for(d in c.ga){var k=c.ga[d]<<1;if(2>k)break;for(var g=0;2>g;g++)for(var f=ia(k+g),f=ha(a,f[0],f[1],f[2]),p=0;1024>p;p++)b[e++]=f[p]}return b}function ka(a){var c=T(a,"test.rnd");if(c)return ja(a,c)}
function la(a){S(a,function(c){if(16>c.K&&0==c.T){var b=R(new Q(a),c);console.log(c.D+" "+c.B+" "+b.ra)}return!1})}function U(a){var c=new Uint8Array(390);(function(a,b){S(a,function(a){if(16>a.K)for(var c in a.O)b[a.O[c]]=!0;return!1})})(a,c);a=[];for(var b=2;b<c.length;b++)c[b]||a.push(b);return a}
function ma(a,c,b){var e=U(a);if(e.length<b.length/2048)console.log("Disk full, remaining clusters:",e.length);else if(c=function(a,b,c,d){var e=0,k=0;S(a,function(a){if(16<=a.K){console.log("saveFile: using header ",a.Fa,a.D,a.B);b.U=Math.ceil(d/128);b.T=k;k+=1;128<b.U&&(b.U=128);for(var f=0;8>f;f+=1)b.O[f]=0<d?c[e]:0,0<d&&(d-=2048,e++);a=a.Ga;f=0;a[f++]=b.K;for(var g=b.D+"        ",h=0;8>h;h+=1)a[f+h]=g.charCodeAt(h);f+=8;g=b.B+"   ";for(h=0;3>h;h+=1)a[f+h]=g.charCodeAt(h);f+=3;a[f++]=b.T;a[f++]=
b.Ha;a[f++]=b.Ia;a[f++]=b.U;for(h=0;8>h;h++)a[f++]=b.O[h]&255,a[f++]=b.O[h]>>8&255;if(0>=d)return!0}});return e}(a,ea(new P,c),e,b.length),0!=c)for(var d=0,k=0;k<c&&d<b.length;k+=1)for(var g=e[k]<<1,f=0;2>f;f++)for(var p=ia(g+f),p=ha(a,p[0],p[1],p[2]),l=0;1024>l;l++)p[l]=b[d++]}
function na(a){console.log("List all files:");S(a,function(b){16>b.K&&0==b.T&&console.log("File: ",b.D,".",b.B," header=",b," dirent=",R(new Q(a),b))});console.log("Find pip.com:");var c=T(a,"pip.com");if(c)console.log("Found:",c);else throw"File was not found";var b=ja(a,c),c=[195,206,4,201,0,0,201,0,0,26,0,0,0,0,0,0,40,73,78,80,58,47,79,85,84,58,83,80,65,67,69,41];console.log("Read bytes:",function(a){var b="";for(d in a)b+=a[d].toString(16)+" ";return b}(b.subarray(0,32)));for(var e=!0,d=0;d<c.length;d+=
1)if(e&=b[d]===c[d],!e){console.log("Contents mismatch: expected 0x"+c[d].toString(16)+" got "+b[d].toString(16));debugger}console.log("File reading seems to be ok");console.log("Which clusters are unallocated:");b=U(a);console.log(b);console.log("Creating new file");b=new Uint8Array(54321);for(d=b.length;0<=--d;b[d]=255*Math.random());ma(a,"test.rnd",b);console.log("List all files:");S(a,function(b){16>b.K&&0==b.T&&console.log("File: ",b.D,".",b.B," header=",b," dirent=",R(new Q(a),b))});console.log("Searching for new file:");
c=T(a,"test.rnd");if(!c){console.log("test.rnd not found");debugger}console.log("found, comparing contents");c=ka(a);if(!c){console.log("Could not read file");debugger;throw"";}for(d=0;d<b.length;d++)if(b[d]!==c[d]){console.log("Contents mismatch pos=",d,"expected=",b[d].toString(16),"got=",c[d].toString(16));debugger;throw"";}console.log("Which clusters are unallocated:");b=U(a);console.log(b);console.log("All tests done");debugger};function V(){this.g=this.I=0;this.h=3;this.c=1;this.j=this.value=0;this.l=!1;this.o=this.m=0;this.f=void 0;this.a=this.b=!1;this.L=0;oa(this,0)}function oa(a,c,b){a.J(8);a.L=8;2==(c&4)?a.j=2:3==(c&4)?a.j=3:a.j=c;switch(a.j){case 0:a.c=0;a.l=!0;a.a=!1;break;case 1:a.c=1;a.a=!1;a.l=!0;break;case 2:a.c=1;a.a=!1;break;default:a.c=1,a.a=!1}a.b=!1;a.h=b;a.g=0}
function pa(a){a.J(0);a.L=0;var c;switch(a.h){case 1:return c=a.I?a.I:a.value,a.I=void 0,c&255;case 2:return c=a.I?a.I:a.value,a.I=void 0,c>>8&255;case 3:switch(c=a.I?a.I:a.value,a.g){case 0:return a.g=1,c&255;case 1:return a.I=void 0,a.g=0,c>>8&255}}return 0}
V.prototype.J=function(a){if(0!==this.L){a-=this.L;if(0>a)return this.L=-a,this.c;this.L=0}switch(this.j){case 0:this.b&&(this.value=this.f,this.a=!0,this.b=!1);this.a&&(this.value-=a,0>=this.value&&(this.value+=65535,this.l&&(this.c=1,this.l=!1)));break;case 1:!this.a&&this.b&&(this.a=!0,a-=3);this.b=!1;this.a&&0<a&&(this.value-=a,0>=this.value&&(this.value+=this.f));break;case 2:!this.a&&this.b&&(this.value=this.f,this.a=!0);this.b=!1;this.a&&0<a&&(this.value-=a,0>=this.value&&(this.value+=this.f));
break;case 3:!this.a&&this.b&&(this.value=this.f,this.a=!0,1==(this.value&1)&&(this.value-=0===this.c?3:1,--a)),this.b=!1,this.a&&0>=(this.value-=a<<1)&&(this.value+=this.f,this.c^=1,1==(this.value&1)&&(this.value-=0===this.c?3:1,this.L=1))}return this.c};function qa(){this.a=[new V,new V,new V];this.b=0}
function L(a,c,b){switch(c&3){case 3:a.b=b;c=b>>1&3;var e=b>>4&3;b=a.a[b>>6&3];0===e?(b.J(6),b.L=6,b.I=b.value):oa(b,c,e);break;default:if(a=a.a[c&3],a.J(8),a.L=8,3==a.h)switch(a.g){case 0:a.m=b;a.g=1;break;case 1:a.o=b,a.g=0,a.f=a.o<<8&65535|a.m&255,a.b=!0}else 1==a.h?(a.value=a.value&65280|b,a.value&=65535,a.f=a.value,a.b=!0):2==a.h&&(a.value=a.value&255|b<<8,a.value&=65535,a.f=a.value,a.b=!0)}}qa.prototype.qa=function(a){switch(a&3){case 3:return this.b;default:return pa(this.a[a&3])}};
qa.prototype.J=function(a){return this.a[0].J(a)+this.a[1].J(a)+this.a[2].J(a)};function ra(a){this.c=a;this.a=this.b=0}ra.prototype.step=function(a){this.b+=this.c.J(a);this.a+=8};function sa(a,c,b,e,d){this.P=!1;this.ia=new Uint32Array(16);this.l=a;this.X=c;this.na=b;this.b=d;this.A=e;this.Ma=function(){};this.La=function(){};this.za=function(){};this.g=function(){};this.c=152;this.a=this.j=this.ha=255;this.o=0;this.S=this.R=this.C=255;this.m=this.h=this.f=void 0}
sa.prototype.input=function(a){var c=255;switch(a){case 0:c=255;break;case 1:c=this.a&15|16|(this.l.Da?0:32)|(this.l.Ra?0:64)|(this.l.Pa?0:128);break;case 2:0!==(this.c&2)?c=this.l.qa(~this.ha):c=255;break;case 3:c=0===(this.c&16)?0:255;break;case 4:c=this.o;break;case 5:c=this.S;break;case 6:c=this.R;break;case 7:c=this.C;break;case 8:case 9:case 10:case 11:return this.X.qa(~(a&3));case 20:case 21:c=this.A.read(a&1);break;case 24:c=this.b.read(3);break;case 25:c=this.b.read(2);break;case 26:c=this.b.read(1);
break;case 27:c=this.b.read(0)}return c};fullscreen=function(a){if(document.mozFullScreen||document.webkitIsFullScreen)document.a?document.a():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen();else{var c=document.getElementById("canvasdiv");c.a?c.a():c.mozRequestFullScreen?c.mozRequestFullScreen():c.webkitRequestFullScreen?c.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):1!=a&&alert("Fullscreen not supported. Try Firefox or Chrome.")}};
fullscreener=new function(){this.exec=function(){fullscreen()}};zip.workerScriptsPath="./zip.js/WebContent/";memory=new ta;
keyboard2=new function(){this.c=new Uint8Array(8);this.Pa=this.Ra=this.Da=!1;this.onreset=function(){};this.b=function(a){if(window.event){try{window.event.keyCode=0}catch(c){}window.event.returnValue=!1;window.event.cancelBubble=!0}a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation()};var a=this;this.g=function(b){var c=document.all?event.keyCode:b.which;a.b(b);if(122===c||123===c)a.onreset(122===c);else a.a(c,!1);return!1};this.h=function(b){var c=document.all?event.keyCode:
b.which;a.b(b);122!==c&&123!==c&&a.a(c,!0);return!1};var c={32:[7,128],192:[7,64],221:[7,32],220:[7,16],219:[7,8],90:[7,4],89:[7,2],88:[7,1],87:[6,128],86:[6,64],85:[6,32],84:[6,16],83:[6,8],82:[6,4],81:[6,2],80:[6,1],79:[5,128],78:[5,64],77:[5,32],76:[5,16],75:[5,8],74:[5,4],73:[5,2],72:[5,1],71:[4,128],70:[4,64],69:[4,32],68:[4,16],67:[4,8],66:[4,4],65:[4,2],191:[4,1],191:[3,128],190:[3,64],187:[3,32],188:[3,16],186:[3,8],222:[3,4],57:[3,2],56:[3,1],55:[2,128],54:[2,64],53:[2,32],52:[2,16],51:[2,
8],50:[2,4],49:[2,2],48:[2,1],116:[1,128],115:[1,64],114:[1,32],113:[1,16],112:[1,8],27:[1,4],308:[1,2],220:[1,1],40:[0,128],39:[0,64],38:[0,32],37:[0,16],8:[0,8],13:[0,4],18:[0,2],9:[0,1]};this.a=function(a,e){var d,k,g;d=e?function(a,b,c){a[b]&=~c}:function(a,b,c){a[b]|=c};switch(a){case 16:this.Da=!e;break;case 17:this.Ra=!e;break;case 117:case 91:case 93:this.Pa=!e;break;default:8==a&&this.Da&&(a=308);61==a?a=187:59==a&&(a=186);var f=c[a];f&&(k=f[0],g=f[1]);void 0!==k&&d(this.c,k,g)}};this.qa=
function(a){for(var c=0,d=0;8>d;d+=1)0!==(a&1)&&(c|=this.c[d]),a>>=1;return~c&255};this.f=function(){document.onkeypress=function(){return!1};document.onkeydown=this.g;document.onkeyup=this.h}};keyboard2.f();timer=new qa;ay=new M;
floppy=new (function(){function a(){this.log=!1;this.ja=null;this.Ba=9;this.la=512;this.Ka=1;this.ka=this.Aa=this.ba=this.position=this.ma=this.track=this.data=0;this.V=new Uint8Array(6);this.$a={128:0,256:1,512:2,1024:3}}function c(){this.v=!1;this.sa=[new a,new a,new a,new a];this.da=0;this.H=this.sa[0];this.i=this.ca=this.$=this.w=this.Y=this.Z=0;new Uint8Array(8);this.W=0;this.pa=2;this.F=this.pa+1;this.ea=1}var b={};a.prototype.ua=function(){return null!==this.ja};a.prototype.wa=function(a,b){this.name=
a;var c=b.length,g=new Uint8Array(c);if(b){var f;if("string"==typeof b)for(f=0;f<c;f++)g[f]=b.charCodeAt(f);else for(f=0;f<c;f++)g[f]=b[f]}this.ja=g;this.Wa()};a.prototype.seek=function(a,b,c){null!==this.ja&&(this.position=(a*this.Ba*this.Ka+this.Ba*c+(0!==b?b-1:0))*this.la,this.track=a,this.ma=c,console.log("FD1793: disk seek position:",O.b(this.position),"(side:"+this.ma+",trk:"+this.track+",sec:"+b+")"))};a.prototype.Ya=function(a){this.Aa=this.la;this.ka=this.ba=0;this.Qa=a;this.seek(this.track,
this.Qa,this.ma)};a.prototype.Xa=function(){this.Aa=6;this.ka=1;this.ba=0;this.V[0]=this.track;this.V[1]=this.ma;this.V[2]=this.Qa;this.V[3]=this.$a[this.la];this.V[4]=0;this.V[5]=0};a.prototype.read=function(){var a=!0;this.ba<this.Aa?(a=!1,this.data=this.ka?this.V[this.ba]:this.ja[this.position+this.ba],this.ba++):this.log&&console.log("FD1793: read finished src:",this.ka);return a};a.prototype.Wa=function(){this.ua()?(this.Ka=2,this.la=1024,this.Ba=5):console.warn("FD1793: no disk")};c.prototype.wa=
function(a,b,c){if(0>a||3<a)throw"FD1793: illegal drive:"+a;this.v&&console.log("FD1793: loadDsk: "+b);this.sa[a].wa(b,c)};c.prototype.exec=function(){var a;if(1==this.ca||2==this.ca){if(this.i&2)throw"invalid read";(a=this.H.read())?(this.i&=-2,this.Z=1):(this.i|=2,this.Y=this.H.data);this.v&&console.log("FD1793: exec - read done, finished:",a,"data:",O.a(this.Y),"status:",O.a(this.i))}else this.i&=-2};c.prototype.read=function(a){var b=0;this.i=this.H.ua()?this.i&-129:this.i|128;switch(a){case 0:b=
this.i;this.i&1&&(0>this.F?(b&=-2,++this.F):this.F<this.pa?++this.F:this.F===this.pa&&(++this.F,this.exec(),b=this.i));this.Z=0;break;case 1:b=this.w;break;case 2:b=this.$;break;case 3:this.i&2||console.log("reading too much!");b=this.Y;this.i&=-3;this.exec();break;case 4:this.i&1&&this.exec();b=this.Z|(this.i&2?128:0);break;default:console.warn("FD1793: invalid port read");debugger}this.v&&console.log("FD1793: read port:",a,"result:",O.a(b),"status:",O.a(this.i));return b};c.prototype.Va=function(a){var b=
a>>>4,c=a&15,g,f;g=f=c&1;this.ca=this.Z=0;console.log("FD1793: CMD=",O.a(a));switch(b){case 0:this.v&&console.log("FD1793: CMD restore");this.Z=1;this.H.ua()?(this.w=0,this.H.seek(this.w,1,this.da)):this.i|=16;break;case 1:this.v&&console.log("FD1793: CMD seek",O.a(c));this.H.seek(this.Y,this.$,this.da);this.w=this.Y;this.Z=1;this.i|=1;this.F=this.W;break;case 2:case 3:this.v&&console.log("FD1793: CMD step",g);this.w+=this.ea;0>this.w&&(this.w=0);this.F=this.W;this.i|=1;break;case 4:case 5:this.v&&
console.log("FD1793: CMD step in",g);this.ea=1;this.w+=this.ea;this.F=this.W;this.i|=1;break;case 6:case 7:this.v&&console.log("FD1793: CMD step out",g);this.ea=-1;this.w+=this.ea;0>this.w&&(this.w=0);this.F=this.W;this.i|=1;break;case 8:case 9:this.ca=1;this.i|=1;this.H.seek(this.w,this.$,this.da);this.H.Ya(this.$);console.log("FD1793: CMD read sector m:",f,"p:",O.a(c),"sector:",this.$,"status:",O.a(this.i));this.F=this.W;break;case 10:case 11:this.v&&console.log("FD1793: CMD write sector",f);break;
case 12:this.ca=2;this.i|=1;this.H.Xa();this.F=this.W;this.v&&console.log("FD1793: CMD read address m:",f,"p:",O.a(c),"sector:",O.a(this.i));break;case 13:this.v&&console.log("FD1793: CMD force interrupt");break;case 14:this.v&&console.log("FD1793: CMD read track");break;case 15:this.v&&console.log("FD1793: CMD write track")}};c.prototype.write=function(a,b){switch(a){case 0:this.Va(b);break;case 1:this.v&&console.log("FD1793: set track:",b);this.w=b;this.i&=-3;break;case 2:this.v&&console.log("FD1793: set sector:",
b);this.$=b;this.i&=-3;break;case 3:this.v&&console.log("FD1793: set data:",O.a(b));this.Y=b;this.i&=-3;break;case 4:this.H=this.sa[b&3];this.da=~b>>2&1;this.v&&console.log("FD1793: set pr:",O.a(b)," disk select: ",b&3," side: ",this.da);break;default:console.warn("FD1793: invalid port write");debugger}};b.Ua=c;return b}().Ua);io=new sa(keyboard2,timer,memory,ay,floppy);cpu=new n(memory,io);v06c=new ua;v06c.M=0;var va=document.getElementById("frameskip");
v06c.o=function(a,c){va.innerText=v06c.M+" "+c};var W="roms/testtp.rom",wa="chooser-glass",xa="about-panel";
if(location.search){W=location.search.substring(1);if("i"===W[0]){document.body.className+=" fullpage";var X=document.getElementById("canvasdiv");X.className="fullpage";var ya=document.getElementById("outerdiv");ya.parentNode.replaceChild(X,ya);var Y=document.getElementById("chooser-panelcontainer");Y.style.position="absolute";Y.style.top="0";Y.style.left="0";Y.className+=" fullpage";X.parentNode.appendChild(Y);wa="chooser-panelcontainer";Y.style.display="none";var za=document.getElementById("about-panel");
za.className+=" fullpage";X.parentNode.appendChild(za);xa="about-panel";W=W.substring(2)}else if("t"==W[0])throw W=W.substring(2),new Z(W,function(){console.log("Loader test - callback ok")},function(){console.log("Loader test - callback error")},function(a){a=ga(new fa,a);na(a)}),v06c.pause(function(){}),"test ended";console.log("user url=",W)}boot=void 0;_onfocus=function(){v06c.Ca.Ja(!1);v06c.Za()};_onblur=function(){v06c.Ca.Ja(!0);v06c.pause(function(){})};
window.addEventListener("load",function(){window.addEventListener("focus",_onfocus);window.addEventListener("blur",_onblur)});keyboard2.onreset=function(a){a&&boot&&Aa(boot);v06c.oa(a)};io.g=function(a){window.parent.ruslat&&window.parent.ruslat(a)};var Ba=null;
function Ca(){console.log("loadUserRom url=",W);(new Z(W,function(a,c){v06c.pause(function(){Da(a,c);v06c.oa(!1)})},function(){console.log("ROM could not be loaded from: ",W)},function(a){console.log("Smells like a floppy image: ",W);floppy.wa(0,W,a)},wa,"chooserpanel")).b()}new Z("boot/boots.bin",function(a){boot=a;v06c.pause(function(){Da([],0);Aa(a);v06c.oa(!0);Ba&&(W=Ba);Ca()})},function(){console.log("Cannot load bootloader, not a problem for loading roms")});
about=function(a){aboot=document.getElementById(xa);a?(aboot.className+=" visible",aboot.style.opacity=1):(aboot.className=aboot.className.substring(0,aboot.className.length-8),aboot.style.opacity=0)};blksbr=function(a){keyboard2.onreset(a)};sideload=function(a){Ba=a};window.parent.registerHooks&&window.parent.registerHooks({about:about,blksbr:blksbr,sideload:sideload});function ta(){this.s=new Uint8Array(327680);this.aa=void 0;for(var a=0;a<this.s.length;a++)this.s[a]=0;this.xa=this.ya=!1;this.Oa=this.Na=0}function Ea(a,c,b){if(a.xa||a.ya){if(a.ya&&void 0!==b&&b)return c+(a.Oa<<16);if(a.xa&&40960<=c&&57344>c)return c+(a.Na<<16)}return c}ta.prototype.read=function(a,c){return this.aa&&a<this.aa.length?this.aa[a]:this.s[Ea(this,a&65535,c)]};ta.prototype.write=function(a,c,b){this.s[Ea(this,a&65535,b)]=c};
function Da(a,c){var b=memory,e,d;for(e=b.s.length;0<=--e;)b.s[e]=0;e=0;for(d=a.length;e<d;e++)b.write(c+e,a[e],!1)}function Aa(a){var c=memory;c.aa=new Uint8Array(a.length);for(var b=a.length;0<=--b;)c.aa[b]=a[b]};function Z(a,c,b,e,d,k){function g(a){var b={},d;for(d in a)if(b.fa=d,b.target=document.getElementById(a[b.fa]),b.target){if("INPUT"===b.target.tagName){var e=function(b){return function(){var d=document.getElementById(a[b.fa]);console.log("fileSelectHandler e=",d.files[0]);Z.prototype.a&&(Z.prototype.a.style.display="none",Z.prototype.a=void 0);f(d.files[0].name,d.files[0],c);var g=document.createElement("input");g.className="upload";g.type="file";g.name="fileselect[]";g.addEventListener("change",
e);d.parentNode.replaceChild(g,d);g.id="fileselect"}}(b);b.target.addEventListener("change",e,!1)}else"CANVAS"===b.target.tagName&&(b.target.g=function(a){a.preventDefault()},b.target.c=function(a){return function(b){b.preventDefault();a.target.parentNode.className+=" dragover"}}(b),b.target.f=function(a){return function(b){b.preventDefault();b=a.target.parentNode;b.className=b.className.replace(/ dragover/g,"")}}(b),b.target.b=function(a){a.preventDefault()},b.target.h=function(a){return function(b){b.preventDefault();
var d=a.target.parentNode;d.className=d.className.replace(/ dragover/g,"");f(b.dataTransfer.files[0].name,b.dataTransfer.files[0],c)}}(b));b={fa:b.fa,target:b.target}}else console.log("initDrop: cannot find element ",a[b.fa])}function f(a,b,c){zip.createReader(new zip.BlobReader(b),function(a){a.getEntries(function(a){if(a.length){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);1==b.length?y(b[0]):1<b.length&&p(a)}})},function(d){console.log("unzip",d," - trying as rom or fdd");a.toLowerCase().endsWith("fdd")?
z(b,e,0):z(b,c,a.toLowerCase().endsWith("r0m")?0:256)})}function p(a){var b=document.getElementById(d),c=document.getElementById(k),e=document.createElement("div");e.id="buildhdr";c.appendChild(e);e.innerText="[OR BUILD A BOOTABLE FLOPPY IMAGE]";(function(a){e.onclick=function(){b.style.display="none";h(a)}})(a);var f=document.createElement("ul");f.className="romchooser-ol";c.appendChild(f);c.style.height="75vh";for(c=0;c<a.length;c+=1){var g=document.createElement("li"),m=document.createElement("a");
m.href="#";g.appendChild(m);m.innerText=a[c].filename;(function(a){g.onclick=function(){b.style.display="none";y(a)}})(a[c]);g.className=l(a[c].filename)?"chooser-li-rom":a[c].filename.toLowerCase().endsWith("fdd")?"chooser-li-fdd":"chooser-li-wtf";f.appendChild(g)}b.style.display="block";Z.prototype.a=b}function l(a){a=a.toLowerCase();return a.endsWith("rom")||a.endsWith("r0m")||a.endsWith("com")||a.endsWith("bin")}function h(a){new Z("roms/ryba.fdd",function(){},function(){},function(b){var c=ga(new fa(0),
b);console.log("\u0440\u044b\u0431\u0430");if(c)for(var d=a.length,f,g=0;g<a.length;g+=1){var h=function(a){if(a){a=a.toUpperCase()+"\n"+String.fromCharCode(26);for(var b=new Uint8Array(a.length),d=0;d<a.length;d++)b[d]=a.charCodeAt(d);ma(c,"initial.sub",b)}e(c.s,0)};(function(b){b.toLowerCase().endsWith("fdd")?(console.log("Not including ",b),0===--d&&h(f)):(console.log("Extracting ",b),b.toLowerCase().endsWith("com")&&(f=b.toUpperCase().split(".")[0]),m(a[g],function(a){console.log("Saving ",b);
ma(c,b,a);0===--d&&(console.log("All files saved, boot"),la(c),h(f))},0))})(a[g].filename)}})}function y(a){var b=a.filename.toLowerCase();b.endsWith("rom")||b.endsWith("r0m")||b.endsWith("bin")||b.endsWith("com")?m(a,c,b.endsWith("r0m")||b.endsWith("bin")?0:256):b.endsWith("fdd")&&m(a,e,function(a){var b=a;if(819200>a.length){var b=new Uint8Array(819200),c;for(c=a.length;0<=--c;b[c]=a[c]);for(c=b.length;--c>=a.length;b[c]=229);}return b})}function m(a,b,c){if(a.blob)z(a.blob,b,c);else{console.log("Unzipping ",
a.filename);var d=new zip.BlobWriter("application/octet-stream");a.getData(d,function(a){z(a,b,c)})}}function z(a,b,c){var d=new FileReader;d.addEventListener("loadend",function(){var a=new Uint8Array(d.result);"function"==typeof c?b(c(a),0):b(a,c)});d.readAsArrayBuffer(a)}this.b=function(){var a=["fileselect","canvas"];window.File&&window.FileList&&window.FileReader&&g(a)};(function(a,b,c){var d=a.name;if(d){var e=a.mem,g,k,l=!1;if(d.endsWith("r0m")){g=new ArrayBuffer(e.length);k=new Uint8Array(g);
for(var m=0;m<k.length;m+=1)k[m]=e[m]}else if(d.endsWith("rom")||d.endsWith("com")){g=new ArrayBuffer(e.length-256);k=new Uint8Array(g);l=256;for(m=0;m<k.length;++l,++m)k[m]=e[l];l=d.endsWith("com")}e=new Blob([g],{type:"application/octet-stream"});l?h([{filename:d,blob:e}]):f(a.name,e,b)}else{var z=new XMLHttpRequest;z.open("GET",a,!0);z.responseType="blob";z.onload=function(){f(a,z.response,b)};z.onerror=function(a){console.log("XMLHttpRequest error",a);c()};z.send()}})(a,c,b)};function Fa(a,c){this.l=new da(a);this.A=new ra(c);this.a=this.j=this.h=null;this.f=this.c=this.g=this.o=0;if("undefined"!=typeof AudioContext){console.debug("AudioContext found");this.b=new (window.AudioContext||window.webkitAudioContext);this.j=this.b.sampleRate;this.o=this.j/1497600;this.m=this.b.createScriptProcessor(2048,0,2);this.a=this.b.createGain();this.a.gain.value=1;var b=this;this.m.onaudioprocess=function(a){if(2048<=(b.c-b.f&8191)){var c=a.outputBuffer;a=c.getChannelData(0);for(var c=
c.getChannelData(1),k=b.f,g=b.h,f=0;2048>f;)a[f]=c[f]=g[k],f+=1,k+=1,a[f]=c[f]=g[k],f+=1,k+=1,a[f]=c[f]=g[k],f+=1,k+=1,a[f]=c[f]=g[k],f+=1,k+=1;b.f=k&8191}};this.m.connect(this.a);this.a.connect(this.b.destination);this.C=!0}this.C&&(this.h=new Float32Array(8192));this.Ja=function(a){return function(b){a.a&&(a.a.gain.value=b?0:1)}}(this)};function ua(){var a=cpu,c=memory,b=io,e=ay,d=!1,k,g=!0;this.M=0;this.na=c;this.a=a;this.f=b;this.Ca=new Fa(e,this.f.X);var f,p,l,h=!1;this.C=function(){if(void 0===this.c||576!=f||288!=p)if(this.c=document.createElement("canvas"),f=this.c.width=576,p=this.c.height=288,this.A=this.c.getContext("2d"),console.log("bufferContext=",this.A.canvas),this.m=this.A.getImageData(0,0,576,288),this.h.width=1*this.c.width,this.h.height=1*this.c.height,h="undefined"!==typeof Uint8ClampedArray&&this.m.data.buffer){console.debug("Using native packed graphics");
var a=this.m.data.buffer;l=new Uint8ClampedArray(a);this.j=new Uint32Array(a)}else{console.debug("Using manually unpacked graphics");l=this.m.data;for(a=0;a<l.length;a++)l[a]=255;this.j="undefined"!=typeof Int32Array?new Int32Array(165888):Array(165888)}if(!h)for(var b=0,c=0;b<this.j.length;b+=1)a=this.j[b],l[c+0]=a&255,l[c+1]=a>>8&255,l[c+2]=a>>16&255,c+=4;this.A.putImageData(this.m,0,0);this.Ta.drawImage(this.c,0,0,this.h.width,this.h.height)};this.N=!1;var y=this;this.Ea=0;this.f.za=function(a){y.Ea=
a};this.ia=this.f.ia;this.b=0;this.Sa=function(){this.h=document.getElementById("canvas");this.h.getContext||alert("Your web browser does not support the 'canvas' tag.\nPlease upgrade/change your browser.");this.Ta=this.h.getContext("2d");this.c=void 0;this.C&&this.C();console.log("initCanvas: screnCanvas=",this.h)};var m=(new Date).getTime();this.l=0;this.S=2;this.R=function(){var a=50/(this.M+1);Ga(this,!0);for(var b=this.M;0<=--b;)Ga(this,!1);this.C();var c=m-(new Date).getTime();if(0>c)8>this.M&&
0>--this.S&&(this.S=2,++this.M,a=50/(this.M+1),this.o&&this.o(0,-c)),c=0,this.l=25,m=(new Date).getTime()+1E3/a;else{this.S=2;if(0<this.M&&20<c){if(0===this.l||0===--this.l)--this.M,this.l=25,this.o&&this.o(0,-c)}else this.l=25;m+=1E3/a}d?(d=!1,g=!0,k&&(k(),k=void 0)):function(a){setTimeout(function(){a.R()},c)}(this)};this.Sa();this.oa=function(a){g=d=!1;this.a.u=0;this.a.G=0;this.a.P=!1;a||(this.na.aa=void 0);L(this.f.X,3,54);L(this.f.X,3,118);L(this.f.X,3,182);e.reset();this.R()};this.Za=function(){g=
d=!1;this.R()};this.pause=function(a){g?a():(k=a,d=!0)}}
function Ga(a,c){a.g||(a.g=new Ha(a.j,a.ia,a.f,a.na.s));a.g.reset();for(var b,e;!a.g.ta;){b=e=-1;var d=a;d.N&&d.a.P&&(d.N=!1,118==d.a.va&&(d.a.u+=1),K(d.a,243),K(d.a,255),d.b+=16);a.g.N=a.g.N&&a.N;d=a.a;K(d,A(d));d=a.a.va;a.b+=a.a.ab;211==d&&(b=a.b-5);-1!=b&&(b=4*b+4,e=b-20);b=a.g.fill(a.b<<2,b,e,c);a.N=a.a.P&&a.g.N;b=a.b-(b>>2);e=a.Ca;var d=a.b-b,k=a.Ea;e.g+=e.o*d/2;if(1<=e.g){--e.g;var g=e.A,f=g.b/g.a;g.b=g.a=0;g=1*f;f=e.l;f.a+=7*f.b;for(var p=f.b=0,l=0;96<=f.a;f.a-=96)p+=f.c.step(),l+=1;k=g+p/
l+k+.005*Math.random();g=e;f=g.c+1&8191;f!=g.f&&(g.h[g.c]=k-.5,g.c=f)}e.A.step(d/2);e.l.step(d);a.b=b}}function Ha(a,c,b,e){this.j=a;this.C=c;this.c=b;this.s=e;this.o=this.l=0;this.reset();var d=this;this.c.La=function(a){d.o=a};this.A=!1;this.c.Ma=function(a){d.A=a}}Ha.prototype.reset=function(){this.h=this.g=this.a=this.b=0;this.m=!0;this.visible=!1;this.f=0;this.N=this.ta=!1};
Ha.prototype.fill=function(a,c,b,e){var d=this.j,k=this.C,g;for(g=0;g<a&&!this.ta;g+=2){var f=this.b-24,p=this.m||128>f||640<=f;if(p)this.g=0,f=this.o;else{if(0===(f&15)){var f=(this.g&255)<<8|this.h&255,l=this.s;this.l=l[32768+f]|l[40960+f]<<8|l[49152+f]<<16|l[57344+f]<<24;this.g+=1}f=this.l;this.l=f<<1&4278124286;f=f>>4&8|f>>13&4|f>>22&2|f>>31&1}if(g===c&&(l=this.c,void 0!==l.f)){var h=l,y=l.f,m=l.h;switch(y){case 0:h.c=m;y=h.a&8;0===(h.c&128)?(m=h.c>>1&7,h.a=1===(h.c&1)?h.a|1<<m:h.a&~(1<<m),h.za(h.a&
1)):h.ha=h.j=h.a=0;(h.a&8)!=y&&h.g&&h.g(0===(h.a&8));break;case 1:y=h.a&8;h.a=m;h.za(h.a&1);(h.a&8)!=y&&h.g&&h.g(0===(h.a&8));break;case 2:h.j=m;h.La(h.j&15);h.Ma(0!==(h.j&16));break;case 3:h.ha=m;break;case 4:h.o=m;break;case 5:h.S=m;break;case 6:h.R=m;break;case 7:h.C=m;break;case 12:case 13:case 14:case 15:h.m=m;break;case 16:h=h.na;h.ya=0!==(m&16);h.xa=0!==(m&32);h.Na=(m&3)+1;h.Oa=((m&12)>>2)+1;break;case 20:case 21:h.A.write(y&1,m);break;case 24:h.b.write(3,m);break;case 25:h.b.write(2,m);break;
case 26:h.b.write(1,m);break;case 27:h.b.write(0,m);break;case 28:h.b.write(4,m)}l.f=l.h=void 0}g===b&&(l=this.c,h=l.m,void 0===h&&12===l.f&&(h=l.h,l.f=l.h=void 0),void 0!==h&&(l.ia[f]=4278190080|(h&192)>>6<<22|(h&56)>>3<<13|(h&7)<<5,l.m=void 0));this.visible&&(l=this.b-120,0<=l&&576>l&&(this.A&&!p?(d[this.f++]=k[f&3],d[this.f++]=k[f&12]):(p=k[f],d[this.f++]=p,d[this.f++]=p)));this.b+=2;768===this.b&&(p=e,this.b=0,this.a+=1,!this.m&&0>--this.h&&(this.h=255),this.m=40>this.a||296<=this.a,this.visible=
this.visible||p&&24===this.a,312===this.a&&(this.a=0,this.visible=!1,this.ta=!0));40===this.a&&150===this.b?this.h=this.c.ha:0===this.a&&176===this.b&&(this.N=!0)}return g};
//# sourceMappingURL=vector06js.map
