/**********************************************************************
 * Extern for zip
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var zip = {
  "Reader": function () {},
  "Writer": function () {},
  "BlobReader": function () {},
  "Data64URIReader": function () {},
  "TextReader": function () {},
  "BlobWriter": function () {},
  "Data64URIWriter": function () {},
  "TextWriter": function () {},
  "createReader": function () {},
  "createWriter": function () {},
  "useWebWorkers": {},
  "workerScriptsPath": {},
  "workerScripts": {}
};
zip.Writer.prototype = {
  "getData": function () {}
};
zip.BlobReader.prototype = {
  "constructor": function () {},
  "getEntries": function () {}
};
zip.Data64URIReader.prototype = {
  "constructor": function () {}
};
zip.TextReader.prototype = {
  "constructor": function () {}
};
zip.BlobWriter.prototype = {
  "constructor": function () {},
  "getData": function () {}
};
zip.Data64URIWriter.prototype = {
  "constructor": function () {},
  "getData": function () {}
};
zip.TextWriter.prototype = {
  "constructor": function () {},
  "getData": function () {}
};
/**********************************************************************
 * End Generated Extern for zip
/**********************************************************************/
